### ISSUE TITLE
ROW_FORMAT not respected in alter statements

### ISSUE THREAD

**Issue by virenderg** [JSQLParser/JSqlParser#1033]
**Describe the bug**
Adding ROW_TYPE as part of alter statement gives error while parsing SQL: 

**To Reproduce**
ALTER TABLE `basic_test_case` ADD COLUMN `display_name` varchar(512) NOT NULL DEFAULT '' AFTER `name`, ADD KEY `test_case_status` (`test_case_status`), add KEY `display_name` (`display_name`), ROW_FORMAT=DYNAMIC;

Encountered unexpected token: "ROW_FORMAT" <S_IDENTIFIER>
    at line 16, column 391.
Was expecting one of:
    "ADD"
    "ALGORITHM"
    "ALTER"
    "CHANGE"
    "COMMENT"
    "DROP"
    "MODIFY"
    "RENAME"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:25031)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:24875)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterExpression(CCJSqlParser.java:15646)
	at net.sf.jsqlparser.parser.CCJSqlParser.AlterTable(CCJSqlParser.java:15683)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:159)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:578)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:149)
	... 21 common frames omitted

**Expected behavior**
ROW_FORMAT should be recognized in alter, like it is in create table. 

**System**
 - Database you are using: MySQL
- Java Version: 1.8.0_231
- JSqlParser version: 3.2

**Comment by mo3000** [comment]
ROW_FORMAT don't has a keyword defination in jsqlparser.jjt, so it is accidently supportted in create table.

**Comment by virenderg** [comment]
ROW_FORMAT is a valid keyword. Is there a place I can ask to add it to jsqlparser.jjt?

**Comment by manticore-projects** [comment]
Greetings!

The issue is not about the particular `ROW_FORMAT` but rather about the supported `ALTER ...` operations. There was a lack of support for altering the table properties.

I have added a new `UNSPECIFIC` operation which simply will route through all tokens, when no different `ALTER ...` operation has matched before. This solution is very flexible and your statement will parse, but if your are interested in the content of the `UNSPECIFIC` operation you will need to process the `optionalSpecifier` of the `AlterExpression` by yourself.
