### ISSUE TITLE
Help getting started :)

### ISSUE THREAD

**Issue by kirajen** [JSQLParser/JSqlParser#1085]
Hi everyone!

I just spun up a maven project, and tested out the JSqlParser using the examples in a wiki such as the table name finder - cool stuff! Im struggling to find any API documentation however, and have trouble moving on. 

My project revolves around data lineage/column impact analysis, where I need to extract the input tables/fields from SQL Server views, and potentially also stored procedures.  Any help would be highly appreciated.

Thanks in advance,
Kira

**Comment by wumpz** [comment]
So when I release JSqlParser the complete API (JavaDoc) wanders to maven central as well:

    https://repo1.maven.org/maven2/com/github/jsqlparser/jsqlparser/3.2/

However, maybe I should consider to build a *gh-pages* branch and publish the JavaDocs there. 

When you have questions, just ask. No problem. If it is getting too time-consuming, we will find a solution. :)

One first advice: Since version 3 of JSqlParser brackets are considered per default array addressing. Since you are using SqlServer, those brackets are used for object name quotation, like:

    select [mycol] from [mytable]

Look for instance into #1001. You have to use something like:

    CCJSqlParserUtil.parse("select * from mytable", parser -> parser.withSquareBracketQuotation(true));

to switch this bracket processing in JSqlParser.
