### ISSUE TITLE
SQLServer中带关键字[status]的查询语句报错

### ISSUE THREAD

**Issue by onlyas** [JSQLParser/JSqlParser#1117]
报错：
Caused by: net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "[" "["

SQLServer语句：
select  bh, dh, xh,[status] from tb_test with(nolock)  where  bh='123'  order by  bh

版本：
- Java 1.8
- JSqlParser 3.2

**Comment by wumpz** [comment]
Since version 3 of JSqlParser brackets are considered per default array addressing. Since you are using SqlServer, those brackets are used for object name quotation, like:

select [mycol] from [mytable]
Look for instance into #1001. You have to use something like:

CCJSqlParserUtil.parse("select * from mytable", parser -> parser.withSquareBracketQuotation(true));
to switch this bracket processing in JSqlParser.

**Comment by onlyas** [comment]
thank you,谢谢
