### ISSUE TITLE
Square bracket expression

### ISSUE THREAD

**Issue by karth06** [JSQLParser/JSqlParser#1159]
Iam not able to parse expression with square brackets for example [sample_data].[travel_details]
how do i parse this expression.
Can you please help

database:sql-server

**Comment by wumpz** [comment]
This is the default behaviour of JSqlParser now, because this bracket quotation of SqlServer collides with array expressions of other databases. Since version 3 of JSqlParser brackets are considered per default array addressing. Since you are using SqlServer, those brackets are used for object name quotation, like:

    select [mycol] from [mytable]

Look for instance into #1001. You have to use something like:

    CCJSqlParserUtil.parse("select * from mytable", parser -> parser.withSquareBracketQuotation(true));

to enable this bracket processing in JSqlParser.

**Comment by karth06** [comment]
i will be only passing **tablename.column** name not the whole select query
for example:
**[travel_data].[travel_id]**

methods like CCJSqlParserUtil.parseExpression() or CCJSqlParserUtil.parseCondExpression() is not able to parse the above mentioned statement

**Comment by wumpz** [comment]
I added this parser modification into parseExpression and parseCondExpression as well. Now you can do this:

```java
Expression result = CCJSqlParserUtil.parseExpression("[travel_data].[travel_id]", false, 
                parser -> parser.withSquareBracketQuotation(true));
Expression result2 = CCJSqlParserUtil.parseCondExpression("[travel_data].[travel_id]", false, 
                parser -> parser.withSquareBracketQuotation(true));
```

**Comment by karth06** [comment]
let me try this
