### ISSUE TITLE
<S_CHAR_LITERAL> wrongly matches the chars with '

### ISSUE THREAD

**Issue by ZhaoRuidong** [JSQLParser/JSqlParser#1172]
**Describe the bug**

**To Reproduce**
1. Example SQL
`SELECT A ALIA1,
          CASE
             WHEN B LIKE 'ABC\_%' ESCAPE '\' THEN 'DEF'
             ELSE 'CCCC'
          END
             AS OBJ_SUB_TYPE FROM TABLE2`

**Expected behavior**
<S_CHAR_LITERAL> should match the  [ '\\' ] rather than [ '\' THEN ']

**System**
 - Database you are using Oracle
- Java Version 1.8
- JSqlParser version 4.0

**Comment by ZhaoRuidong** [comment]
I'm confused to the explanation of  ~["0"-"9","a"-"z","A"-"Z","'","-"] matches any single character that is not a digit. [https://www.engr.mun.ca/~theo/JavaCC-Tutorial/javacc-tutorial.pdf](url) mentioned in Chap 1.4.1

**Comment by wumpz** [comment]
This is indeed an open problem of JSqlparser. Since we are supporting multiple databases the escaping of single quotes can be  **\\'** or **''**. This leads unfortunately to this behavior. 

Until now I was not able to produce a better regular expression. One solution would be to make this processing either way optional like for instance bracket parsing. Then only one way would be successful and then a correction would be easier.

> I'm confused to the explanation of ~["0"-"9","a"-"z","A"-"Z","'","-"] matches any single character that is not a digit. https://www.engr.mun.ca/~theo/JavaCC-Tutorial/javacc-tutorial.pdf mentioned in Chap 1.4.1

Additionally, I don't see the connection between your second question to this issue.
