### ISSUE TITLE
在SQL中，同时使用NOT REGEXP 就会报错

### ISSUE THREAD

**Issue by 2406450951** [JSQLParser/JSqlParser#1199]
CCJSqlParserManager parserManager = new CCJSqlParserManager();
String sql = "select id,name FROM teacher WHERE phone not regexp '^(13[0-9]|14[5|7]|15[0|1|2|3|4|5|6|7|8|9]|18[0|1|2|3|5|6|7|8|9])\d{8}$'";        
Select select = null;
        List<String> strItems = new ArrayList<>();
        try {
            select = (Select) parserManager.parse(new StringReader(sql));
            PlainSelect plain = (PlainSelect) select.getSelectBody();
            List<SelectItem> selectItems = plain.getSelectItems();
} catch (JSQLParserException e) {
            e.printStackTrace();
        }

![image](https://user-images.githubusercontent.com/48074721/118752796-5411f400-b896-11eb-8b38-2eee0f95720e.png)

**Comment by manticore-projects** [comment]
Greetings.

Please double check, that you are **using the latest Git JSQLParser commit** because your example parses correctly for me.
You can [test it here online](http://217.160.215.75:8080/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsEsAmAoe70BpYDsCGAtgKYoBiASgPICysALkXgMYAWRATigOoASI5IWAAcWAexxFYAOUpwBAcRAANAAqwA5AD0AFAEYAzAG0ADAFoAnAF0AProAshgKzWA7Dd2OTt6wCZr+6ztrZwA2V2sADmsrWwivXV9-YOswl0joywBKAB0kAG8IgF8AEnUUAG4gA+)

**Comment by 2406450951** [comment]
Thanks
我看到了您发布的最新版本为4.1，而我的版本是4.0，我寻找一下解决方法，
![image](https://user-images.githubusercontent.com/48074721/118754532-df40b900-b899-11eb-849e-6493879c67e7.png)

**Comment by manticore-projects** [comment]
Unfortunately I am not certain, if you would like ask a question or confirm a solution.
But you are save to change the dependency to
```xml
                <dependency>
			<groupId>com.github.jsqlparser</groupId>
			<artifactId>jsqlparser</artifactId>
			<version>4.1-SNAPSHOT</version>
		</dependency>
```

**Comment by 2406450951** [comment]
Thank you
