### ISSUE TITLE
Oracle net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "||" <OP_CONCAT>

### ISSUE THREAD

**Issue by jueding920** [JSQLParser/JSqlParser#1206]
**Describe the bug**

**To Reproduce**
1. Example SQL
2. Parsing this SQL using JSqlParser with this statements
3. Exception
and t.cntr like '%'||?||'%'

**Expected behavior**
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "||" <OP_CONCAT>
**System**
 - Database you are using Oracle
- Java Version jdk8    
- JSqlParser version 4.0

**Comment by manticore-projects** [comment]
Greetings,

this issue is on missing Whitespacing.
When you add proper spaces it will work as expected:
```sql
SELECT *
FROM dual
WHERE t.cntr LIKE '%' || ? || '%'
;
```

You can test this [here online and interactively](http://217.160.215.75:8080/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYBMCuAhgDaIDqAEiKiLAC4B0AxgHa0BOsYAkgNI0DkAUn6wAPqNgB+MRKH9EAbiA+)

**Comment by jueding920** [comment]
thank you

**Comment by wumpz** [comment]
To be more concrete this `?|` is a json operator and so JSqlParser confuses this with your `? || `.

**Comment by manticore-projects** [comment]
Answered and no further question has been asked.
