### ISSUE TITLE
how to write transaction statement for begin commit and rollback 

### ISSUE THREAD

**Issue by doukai** [JSQLParser/JSqlParser#1235]
how to write transaction statement for begin commit and rollback?
any idea about it?
thanks~

**Comment by manticore-projects** [comment]
Good Morning.

You do not state the RDBMS, so lets assume `Oracle`:
![image](https://user-images.githubusercontent.com/18080123/122661199-d5201c00-d1b1-11eb-97b9-73dee3c73d84.png)

Unfortunately I do not think, `ROLLBACK` is supported yet because I just pushed a PR for `ALTER SESSION` and had to define `ROLLBACK` as a new Keyword Token.

Same for `SAVEPOINT`, althought `COMMIT` seems to be supported.

**Comment by doukai** [comment]
Thanks for the answer

**Comment by manticore-projects** [comment]
Please re-open. I will add support for START TRANSACTION, COMMIT and
ROLLBACK at least for the Oracle Dialect eventually.

**Comment by manticore-projects** [comment]
Basic support for Oracle and H2, let me know (with examples) if anything was missing. Cheers.

**Comment by doukai** [comment]
coooool!

**Comment by manticore-projects** [comment]
Careful: the PR has not been accepted yet. You would need to pull from my Repo and compile from source if you want to use the feature immediately. Otherwise you would need to wait for acceptance by @wumpz.

**Comment by wumpz** [comment]
There are some slight merge conflicts.
