### ISSUE TITLE
The bigQuery 'COUNTIF' keyword cannot be parsed.

### ISSUE THREAD

**Issue by proteus1121** [JSQLParser/JSqlParser#1297]
**Describe the bug**
The bigQuery 'COUNTIF' keyword cannot be parsed.
https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#countif

**To Reproduce**
```
SELECT
  COUNTIF(`table`.`test`) AS count_test,
  COUNTIF(`table`.`test` IS FALSE) AS count_non_test
FROM
  `table`
```
**Exception:**
```
Encountered unexpected token: "(" "("
    at line 3, column 10.
```
**Expected behavior**
It's possible to support COUNTIF function? It will be super useful for me. Thanks!

**System**
 - Google Big Query
- Java 11
- JSqlParser version 4.0

**Comment by manticore-projects** [comment]
Greetings.

Please try the latest version 4.1 or 4.2-Snapshot because I can parse your statement without problems. [Your can try it here online and interactively](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEuQPYFcB2AXAlgMwBSwAN0BDAIwBsBTAgOiMoGd0DYBKWAQWFgGMUMA+ukboAUPAkSANAn5Y8hEhWp1hTFgEluAMQ5hQbTtz5p0A1IlRCRo7QCUA8gFlFZKgVEBuIA+)

**Comment by proteus1121** [comment]
@manticore-projects yes, your right, just checked 4.1, works fine, thanks!
