### ISSUE TITLE
Use it to parse MYSql using full-text indexing SQL statements to reproduce the exception

### ISSUE THREAD

**Issue by code81192** [JSQLParser/JSqlParser#1356]
**Describe the bug**
This exception occurred when using MySQL full-text index

**To Reproduce**
Use it to parse MYSql using full-text indexing SQL statements to reproduce the exception
1. Example SQL
SELECT
  t.`mall_id`,
  t.`mall_name`,
  t.`main_image_url`,
  t.`total_goods`,
  t.`total_sales`
FROM
  tb_mall t
WHERE MATCH (t.`mall_name`) AGAINST ('hehe' IN BOOLEAN MODE);
2. Parsing this SQL using JSqlParser with this statements
3. net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "match" "MATCH"

**Expected behavior**

**System**
 - mysql 8
- Java 8
- JSqlParser  4.2

**Comment by manticore-projects** [comment]
Please double check the version of JSQLParser you are using.
It definitely works with JSQLParser-4.3 Snapshot and you can [test it here online and interactively](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsBcB0BbAhgGwwfQJYBMAoeEkgGkVUxwDs0UBTY08y9XGvdAcwewFcAThmYtYFZAgD2CTNm5Sp+AM6iWEpNNk5lmBqoBiAJQDyAWUQAjbOiyJCAdQASIIyFhmAgtEhPYACmRbWnoGAEpYTwBxTwBJADlgOH8AcgALBgyU2ATYACETEwhPeI8TABEQMMIAbiA+)

Since 4.3-Snapshot does not contain any particular fixes regarding your statement, I would have expected JSQLParser-4.2 working too.

**Comment by manticore-projects** [comment]
Works with 4.3-Snapshot and no further question has been asked.
