### ISSUE TITLE
Fuzzing integration by way of OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [JSQLParser/JSqlParser#1400]
Hi!

I was wondering if you would be interested in getting jsqlparser fuzzed by OSS-Fuzz? Fuzzing is a technique for stress-testing applications and OSS-Fuzz is a free service run by Google for fuzzing important open source projects, and it would be great to get jsqlparser integrated with OSS-Fuzz. OSS-Fuzz will run the fuzzers continuously and report back with bug reports when bugs are found. These reports will have full stack traces, input triggers and more. If you are interested, then the only thing needed is an email(s) connected to a Google account that can be used for receiving the bugs reports, which can be put in the configuration file (project.yaml) over at the OSS-Fuzz repository.

I have set up an initial integration with OSS-Fuzz here: https://github.com/google/oss-fuzz/pull/6746 and this PR on the OSS-Fuzz repository includes a simple initial fuzzer. We can always extend with more fuzzers if you are happy to integrate. I would just need an email and then get this PR merged, following that we should be good to go and down the line we can also migrate fuzzers from OSS-Fuzz to jsqlparser owns repository.

**Comment by wumpz** [comment]
@DavidKorczynski So were the advantage of using your product? We are checking with each run as well.

**Comment by manticore-projects** [comment]
I ran Static Code Fuzzing Tests before and I doubt that it works for JSQLParser:

1) the Fuzzer correctly complained about a LOT of DEFAULT constructors not enforcing NULL checks

2) however, there is no good way to correct those because we need exactly these Default Constructors and ALWAYS set the variables after the initiation in the JavaCC productions

The software is what it is: a automatically generated Parser. It is not really a SQL building API (although it could be used for that task too, but not in a fool-proof way.)

**Comment by DavidKorczynski** [comment]
@wumpz am not really sure what you mean by "we are checking each run as well"? Fuzzing is essentially a genetic algorithm that will gradually explore more code coverage of the target code by mutating a given testcase.

@manticore-projects - fuzzing is dynamic and not static analysis. The goal here (in java versus other languages) would be to, e.g. identify unexpected exceptions

**Comment by manticore-projects** [comment]
Hi David,

so you would like to dynamically mutate SQL statements and test if JSQLParser parses them correctly?
If so, how will you know if your statement is valid on what RDBMS?

**Comment by manticore-projects** [comment]
@Wumpz: I am actually somewhat curious to try it out just to prove my expectation wrong.

**Comment by DavidKorczynski** [comment]
What I am simply interested in is seeing whether the code:
```
    try {
      CCJSqlParserUtil.parse(RAND_STRING);
    } catch(JSQLParserException e) { }
```
will ever crash based on a RAND_STRING being any given string. 

We can always try this and if you find it useful: great - if not: we can just remove the project from OSS-Fuzz. Notice other Java projects are being integrated into OSS-Fuzz, e.g. we recently found some issues in GSON json parsing

**Comment by manticore-projects** [comment]
David, please what do you mean by "crash"?
Your example will either

a) parse correctly when the SQL is correct and the Parser understands the SQL
b) throw an error when the SQL is correct but the Parser does not understand the SQL (yet, e.g. missing feature)
c) throw an error when the SQL is incorrect

Nothing of that was a "crash", it just would throw a Parse Exception.
On top of that it might be possible to throw a NPE when build a `Statement` from Java Code.

**Comment by DavidKorczynski** [comment]
Crash in this case simply means throwing an unexpected exception. The goal is to catch all that the function is expected or promises to throw and then use the fuzzer to test that this is indeed the given case.

**Comment by manticore-projects** [comment]
@wumpz : If you ask me, let them try. Its a win win situation: Either they find something, then we will be grateful and I would lose my wager. Or we just will get the expected Parser Exceptions and can sleep well at night.

**Comment by wumpz** [comment]
So why not. But as @manticore-projects already explained, the parser is what it is. Even if your RAND_STRING does produce some kind of valid SQL, if JSqlParser throws an Exception, how do you know, that this Exception is invalid?

With "checking each run" I ment, that tests are running every time a build is made. I said this because I had the impression, that OSS-fuzz would run not every time, but now I think you are triggering each commit. 

1. However, how are the methods specified you are testing? The parser itself has a lot of stuff in it, that is simply generated and does not need to be tested, at least from JSqlParser dev. 
2. How to you specify the tested Strings (SQLs) or do you indeed use randomly generated String?

**Comment by manticore-projects** [comment]
Closed, since no further question has been asked.
