### ISSUE TITLE
checkstyle does not always run - maybe a gradle problem?

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#1423]
After merging multiple PRs there were checkstyle problem within the new sourcecode. Therefore it was either commited without running it or the build did not check it. 

Running the build using maven immediatly fails.

@manticore-projects could you check this?

**Comment by manticore-projects** [comment]
Greetings, definitely not a gradle problem -- but maybe a task dependency problem.

`gradle build` definitely calls the CheckStyle task (explicitly).
`gradle test` does not call the CheckStyle task (because I want to test functionality here, not package/release and also I do not want to get obstructed by code style nonsense while working on stuff).

So if a committer executed `gradle test` only and then pushes, indeed the CheckStyle would not have been executed.

Two options:

1) enforce CheckStyle and PMD during the tests (which I really do not like, because I see those tests as Functional Tests, but not as rule compliance tests)

2) bring back the GIT actions which ran CheckStyle/PMD when a PR was pushed and then indicated failure

I liked option 2 very much.

**Comment by wumpz** [comment]
The problem with 2 is that it would motivate to commit and push not checked sources. That's what I wanted to avoid, at least to make it harder.

**Comment by manticore-projects** [comment]
> The problem with 2 is that it would motivate to commit and push not checked sources. That's what I wanted to avoid, at least to make it harder.

I agree, but what exactly do you want me to do? Currently, the standard command `gradle build` will execute PMD and CheckStyle and Coverage (similar as Maven does).

Of course, anyone could just modify code without calling `build` or `test` and push it and anyone could do that with Maven and Gradle in the same way.

What solution to this problem would you like to see please?

**Comment by wumpz** [comment]
OK. If the standard commands do execute it, then I am fine.
