### ISSUE TITLE
move to junit 5

### ISSUE THREAD

**Issue by wumpz** [JSQLParser/JSqlParser#1427]
At the moment we have a mixture of JUnit 4 and JUnit 5 tests. 

We want to completely move to JUnit 5. 

For this, a new branch was introduced: [move-to-junit5]. Be aware that I removed JUnit 4 completely there, so a lot of compile errors are still there.

Sadly it is not enough to replace the imports:

1. replace imports
2. change assertions with messages: in junit 4 the message was the first parameter in junit 5 its the last
3. change annotation names before, after, ... those are renamed in junit 5

I will start from the bottom to change the stuff (now `TableNamesFinderTest.java`)

To clean things up:

1. remove empty generated before and after methods

**Comment by wumpz** [comment]
First of all I will replace project wide all imports before I will push this branch.

**Comment by wumpz** [comment]
At the moment there are two assertion extensions: hamcrest and assert4j. We will leave that for now.

**Comment by wumpz** [comment]
The switch seems to be faster than I expected. So I will the complete transformation und push for all this new branch to check if all runs perfectly well.

**Comment by wumpz** [comment]
Stumbled right now about some Junit 3 tests. Time to say good bye. ;)

**Comment by wumpz** [comment]
https://github.com/JSQLParser/JSqlParser/tree/move-to-junit5 
is finally there. 

The transformation is at least syntactically complete.

**Comment by wumpz** [comment]
SelectTest.testMultiPartColumnNameWithDatabaseNameAndSchemaName corrected

**Comment by wumpz** [comment]
CreateTableTest works now

all tests are running

could that be merged into master or did I forget something:

1. are all tests executed?
2. should hamcrest be removed (I do prefer assert4j  :) )?
3. should the mocking somehow not exectuted with this new JUnit 5 extension?
4. ...

**Comment by manticore-projects** [comment]
@wumpz , good job.

My recommendation: merge it, its just about tests after all and we can fine tune gradually.
I would like to add one task: The Test SQLs should go into a resource file outside of the Java Test Classes, for better readability and reuse. We could do that much later.

**Comment by wumpz** [comment]
@manticore-projects I thought about that as well but decided against it, at least for all those simple SQL parsing tests, since you would e.g. loose the documentation, method naming, context. Or do you have something different in mind?

**Comment by manticore-projects** [comment]
Yes, I do: for JSQLFormatter I have done something similar and in my opinion it works extremely well:

1) Define one Abstract Test Class which is able to read a SQL Resource File matching the Test Class' name
2) Read that Resource File in a way, that each SQL Statement is labeled by a leading comment naming this particular test, e. g.:
```sql
--- TEST CASE 1
SELECT * from dual;

-- TEST CASE 2
SELECT * from SOMETHING_ELSE;
```

The sample above will define 2 test cases "TEST CASE 1" and "TEST CASE 2";

3) Implement parametrized Test Case Classes for all Statement Types and Expression Classes (implementing  the Abstract Test Class, e.g.
```java
class SelectStatementTest implements AbstractParserTest {
}
```
which would work with a `SelectStatementTest.sql` resource file.

There are 2 disadvantages though:

a) it is harder to run an isolated test only (instead of the whole suite)
b) obviously this does not cover the Mock and/or Java Object based tests, but only the "assertParseAndDeparse" based SQL tests (which are plenty though).

Cheers!

**Comment by manticore-projects** [comment]
Have a look at https://github.com/manticore-projects/jsqlformatter/blob/main/src/test/java/com/manticore/jsqlformatter/StandardOffsetLimitTest.java which illustrates the approach in detail.

**Comment by gitmotte** [comment]
> Yes, I do: for JSQLFormatter I have done something similar and in my opinion it works extremely well:
> 
>     1. Define one Abstract Test Class which is able to read a SQL Resource File matching the Test Class' name
> 
>     2. Read that Resource File in a way, that each SQL Statement is labeled by a leading comment naming this particular test, e. g.:
> 
> 
> ```sql
> --- TEST CASE 1
> SELECT * from dual;
> 
> -- TEST CASE 2
> SELECT * from SOMETHING_ELSE;
> ```
> 
> The sample above will define 2 test cases "TEST CASE 1" and "TEST CASE 2";
> 

There is no need for such special syntax - java has good Property-File support. 

``` 
TEST_CASE_1=SELECT * from dual;

# comment on test case 2: \ properties support line breaks
TEST_CASE_2=SELECT * \
from SOMETHING_ELSE \
where A=B;

```
can be read with
```
Properties prop = new Properties();
prop.load(inputStream);
``` 

>     3. Implement parametrized Test Case Classes for all Statement Types and Expression Classes (implementing  the Abstract Test Class, e.g.
> 
> 
> ```java
> class SelectStatementTest implements AbstractParserTest {
> }
> ```
> 
> which would work with a `SelectStatementTest.sql` resource file.
> 
> There are 2 disadvantages though:
> 
> a) it is harder to run an isolated test only (instead of the whole suite) b) obviously this does not cover the Mock and/or Java Object based tests, but only the "assertParseAndDeparse" based SQL tests (which are plenty though).
> 
> Cheers!

That said, i am also against outsourcing the sql resources, because the readability is lost and as you also noted, the overhead of loading the resource file is unnecessary if you just want to run a test.

**Comment by wumpz** [comment]
merge is done
