### ISSUE TITLE
Parse sql error with offset and limit

### ISSUE THREAD

**Issue by ldbmcs** [JSQLParser/JSqlParser#1449]
**Describe the bug**
parse sql error with offset and limit 

**To Reproduce**
1. Example SQL：`select * from dual OFFSET ? LIMIT ?;`
2. Parsing this SQL using JSqlParser with this statements
    ```java
    @Test
    public void testParseStatements() throws Exception {
        Statements result = CCJSqlParserUtil.parseStatements(
                "select * from dual OFFSET ? LIMIT ?;");
        assertEquals("SELECT * FROM dual OFFSET ? LIMIT ?;\n", result.toString());
    }
    ```
3. Exception

```java
expected: SELECT * FROM dual OFFSET ? LIMIT ?;
but was: SELECT * FROM dual LIMIT ? OFFSET ?;
```

**Expected behavior**

**System**
 - Database you are using
- Java Version 
   1.8
- JSqlParser version
   4.3

**Comment by manticore-projects** [comment]
Greetings.

Indeed, the order of the `LIMIT` and `OFFSET` terms is not observed, but hard-coded in the de-parser.

I am still reluctant to declare that an error, because I do not see any merit in observing the order and am not sure if all RDBMS are flexible regarding this order. Instead, I see it similar to the white-space and comments: it does not add any value to the SQL statement and won't stop the SQL statement to be executed correctly.

So to me, this is a "Won't fix".

However, if you would like to contribute a PR we certainly would accept/merge it.
