### ISSUE TITLE
Get fingerprint from a sql?

### ISSUE THREAD

**Issue by roseduan** [JSQLParser/JSqlParser#1463]
How to get the fingerprint from a specified sql? Is there any implemention in JSqlParser?

**Comment by manticore-projects** [comment]
Greetings,

there is no specific implementation (because it is not really our concern), however you can safely create a distinct fingerprint by:

1) parsing your SQL with JSQLParser
2) de-parsing it (in order to mangle white space and Upper-/Lower-Case spelling)
3) hashing it with your favorite algorithm (e. g. SHA-1)

**Comment by wumpz** [comment]
First you need to specify what you mean by fingerprint. @manticore-projects suggestion is right, if all of your SQL is relevant. But you could also replace concrete values by a e.g. question mark and then 

```sql
select * from mytable where id = 5
```

would by equal to 

```sql
select * from mytable where id = 6
```

**Comment by manticore-projects** [comment]
@wumpz is right of course: For the purpose of execution plans, when Deparsing, you could rewrite all `Values` (String, Date, Double) with `Parameters`, before you hash.

**Comment by haibinz** [comment]
@roseduan 请问获取指纹的问题，您解决了么？

**Comment by haibinz** [comment]
@roseduan Excuse me, have you solved the problem of obtaining fingerprints?

**Comment by manticore-projects** [comment]
Closed, since no further question has been asked.
