### ISSUE TITLE
StackOverflowError in AllColumns expression

### ISSUE THREAD

**Issue by amigalev** [JSQLParser/JSqlParser#1500]
**Describe the bug**
StackOverflowError occurs when select item "count(*)" accepts some parser. I use custom parser, but the same behavior reproduces with SelectDeParser. See code snipped below

**To Reproduce**
Execute the following test:

    @Test
    public void stackOverflowErrorTest() throws JSQLParserException {
        CCJSqlParserManager pm = new CCJSqlParserManager();
        Select select = (Select) pm.parse(new StringReader("select count(*) from some_table"));
        PlainSelect selectBody = (PlainSelect) select.getSelectBody();
        SelectItem selectItem = selectBody.getSelectItems().get(0);
        selectItem.accept(new SelectDeParser());
    }

**Expected behavior**
Correct execution

**System**
 - Database you are using: postgres
- Java Version: liberica jdk 11.0.14
- JSqlParser version: 4.3

**Comment by manticore-projects** [comment]
Greetings.

The statement itself is definitely parsed correctly. You can [check it here online](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEkHsCuA7ALgClgKlgSgCgAxAJQHkBZWAZwQFsBTAfTQEMAjAGwYIG4g+).

Also, shouldn't the `Select` accept the `SelectDeparser` (instead of the `SelectItem`).

**Comment by manticore-projects** [comment]
Good catch, I tip my hat.
