### ISSUE TITLE
When using Update.addColumns(Column... columns) method， the columns will be clear

### ISSUE THREAD

**Issue by blmas** [JSQLParser/JSqlParser#1590]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/39994225/178901608-be77de44-5ed8-4263-b205-cdf12fc79c3f.png">
<img width="414" alt="image" src="https://user-images.githubusercontent.com/39994225/178901651-182e1fc2-d05d-4196-99e6-32f99a6c4abf.png">
<img width="507" alt="image" src="https://user-images.githubusercontent.com/39994225/178901725-87ccf3d4-ec8f-4af5-9b41-9bbf3ffaf7e1.png">
<img width="763" alt="image" src="https://user-images.githubusercontent.com/39994225/178901988-9d6572f5-d887-4180-a311-ab29554594d9.png">

**Comment by wumpz** [comment]
So you wanted to add all columns to the update set and leave already included once intact?

**Comment by manticore-projects** [comment]
Those methods are marked `Deprecated` for a reason. Do not use them!

**Comment by wumpz** [comment]
@manticore-projects The more modern `with` methods use internally the deprecated methods as well. However `addColumns` is not deprecated. So the question is valid. 

@blmas Sorry for not getting you the first time. The problem was that `addColumns` changed directly the internal list and then gave this list to `setColumns` so the clearing was very effective ;) .
