### ISSUE TITLE
table name has hyphen/dash "-" 

### ISSUE THREAD

**Issue by dequn** [JSQLParser/JSqlParser#1636]
In Google BigQuery, a full qualified table name can be like  `pro-ject.dataset.table-name`, having "-" in the database and table part. Though this can resolved by wrapping the full name  with backtick like ``    `pro-ject.dataset.table-name` ``, but it's not very convenient.

**Comment by manticore-projects** [comment]
Greetings.

Sorry to ask: why would people write queries like that and far away from any standard or convention?!
My point is: `pro - ject` == `pro-ject` for the parser. Implementing a differentiation here would make parsing even more expensive because the parser will need to test if this might be an Expression.

**Comment by dequn** [comment]
@manticore-projects  OH yes, BigQuery has a very complex full qualified table name schema, after a hard try, I found it's too hard to support an unquoted table name.
