### ISSUE TITLE
Unexpected token: "IN" "IN"

### ISSUE THREAD

**Issue by LaberionAjvazi** [JSQLParser/JSqlParser#1637]
I am trying to parse a query like : 
`SELECT * FROM some_table WHERE someValue IN (:keys)` 
, where keys will be an input parameter, and I get the following exception 
`net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "IN" "IN"
    at line 1, column 123.`.
From looking at similar issues it seems that `keys` is a reserved keyword for JSQL parser since it causes exception anywhere it is used (e.g. WHERE something = keys or FROM someTable AS keys). Is this the case and if so can I allow parsing of these kind of queries without having to replace the string?

Thanks!

**Comment by manticore-projects** [comment]
Please try the latest JSQLParser 4.6 Snapshot because I can parse your statement without any problems.
You can [try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYGcD2AtgKYD6ALgIYBGANkYgOoASIqIuhRAbhTQK5FYASQBysABSwAXAGsiATxywAlIgDcQA)
