### ISSUE TITLE
Queries with long IN statements take a long time to parse

### ISSUE THREAD

**Issue by PeterGlass** [JSQLParser/JSqlParser#1663]
Parsing is taking a long time with queries having a long IN statement. Below is an example query where the IN clause has 100,000 values:
```
SELECT col1, col2, col3 
FROM testTable
WHERE col1 IN ('value1', 'value2', 'value3', ... , 'value100000')
```
When testing queries like this, it is taking multiple hours to execute. Is this expected behavior? Are there any mitigations to help lower the execution time?

**System**
Java Version: 1.8.0_202
JSqlParser version: 4.5

**Comment by manticore-projects** [comment]
Good Morning.

Thank you for your report.

> Below is an example query where the IN clause has 100,000 values:

This is NOT the way, how an `IN` clause is supposed to be used. Oracle for example limits for good reason the number of parameters, the `IN` clause would accept.

> When testing queries like this, it is taking multiple hours to execute.

Since JSQLParser 4.5 there should be a `timeout` killing your parser, when not returning withing a few seconds. Please double and triple check, that you are indeed using JSQLParser 4.5. No query should run multiple hours, but fail instead.

What you can do now, is this:
1) disable complex parsing in order to parse only simple expressions but not complex expressions for in `IN` clause
2) and/or increase the time-out

```java
// Allow Complex Parsing (which allows nested Expressions, but is much slower)
Statement stmt2 = CCJSqlParserUtil.parse(
                sqlStr
                , parser -> parser
                        .withAllowComplexParsing(false)
                        .withTimeOut(6000)
);
```

How does it working in general: JSQLParser always tried to parse Statements in a simple and fast way unless in reaches the timeout of a few seconds. When this timeout is reached, it tries to parse the Statement again assuming Complex Expressions (e. g. `Sub-Queries` as parameters of your `IN` clause).

So increasing the timeout alone may help already.

**Comment by PeterGlass** [comment]
@manticore-projects Thank you for your response.

I double checked and I was using v4.4 when testing this query, which I'm assuming doesn't have a timeout. Is there a recommended timeout to use? Or a recommended limit to how long a query should be to be executed within a few seconds.

For context I don't have control over submitted queries and I'm trying to find the best point to reject/timeout long parsing queries.

**Comment by manticore-projects** [comment]
Closed when no further question has been asked.
