### ISSUE TITLE
Use of unquoted protected words in column aliases

### ISSUE THREAD

**Issue by cheseaux** [JSQLParser/JSqlParser#1680]
Hi !

I think there is a bug when one uses a protected word as an alias for a column.
This can be demonstrated by the following test (which fails)

```
String sql = "SELECT now() YEAR FROM mytable";
Select select = (Select) CCJSqlParserUtil.parse(sql);
PlainSelect plainSelect = (PlainSelect) select.getSelectBody();
SelectExpressionItem selectExpressionItem = (SelectExpressionItem) plainSelect.getSelectItems().get(0);
assertFalse(selectExpressionItem.getExpression() instanceof IntervalExpression);
```

The alias `YEAR` is being mistaken for an Interval Expression.
By wrapping the alias in double-quotes or using the `AS` keyword this works as expected:

```
SELECT now() \"YEAR\" FROM mytable
SELECT now() AS YEAR FROM mytable
```

**Comment by manticore-projects** [comment]
Greetings,

thank you for reporting, your observation is correct.
Although there is not much we can do about, since it's actually a feature but not a bug. JSQLParser aims to be agnostic to the RDBMS and wants to support as many SQL Dialects as possible in parallel. Sometimes those SQL Dialects collide.

We need to remember that there is a Production `IntervalExpressionWithoutInterval(Expression expr)` which is defined as:
```
token = <K_DATE_LITERAL> { interval.setIntervalType(token.image); }
```

You can see the details here: http://217.160.215.75:8080/jsqlformatter/JSQLFormatter/_static/JSqlParserCC.xhtml#IntervalExpressionWithoutInterval

So anything like `value YEAR` is indeed interpreted as an Interval here and this is correct for at least one of the supported RDBMS and changing it would break the support for this RDBMS.

Example:
```sql

-- H2 returns an error: Data conversion error converting "TIMESTAMP to INTERVAL YEAR"
select now() YEAR

-- H2 returns: INTERVAL '1' YEAR
select 1 YEAR
```

Since we only parse the structure but do not return Records, it is not a problem. You still will get the needed information, just on an unexpected path:

![image](https://user-images.githubusercontent.com/18080123/204516948-c234a3b1-9f8d-4734-a229-d6733111b400.png)

**Comment by manticore-projects** [comment]
[This is where the fun starts!](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20M4UwNiDGAuAECMsCeICGAnZb1A)

**Comment by cheseaux** [comment]
That was a lightning-fast response! Thank you

**Comment by manticore-projects** [comment]
Answered and no further question asked.
