### ISSUE TITLE
Some SQL server syntax does not support parsing

### ISSUE THREAD

**Issue by SconyHui** [JSQLParser/JSqlParser#1682]
Hi,
    I found it unsupported when parsing part of SQLServer syntax.
    example:
    1,  select [id],[name],[age] from [Student]
        Because the column name contains the special symbol "[" or "]"
    2,  declare @flag int
         set @flag = 1
        Because the column name contains the special symbol "@" in SetStatement
    3,  begin
         ...
         end
        This syntax is not supported
    4, use LibName
        go
        ...
        go
        This syntax is not supported

**Comment by manticore-projects** [comment]
Greetings.

Please use the latest JSQLParser 4.5 or better JSQLParser 4.6 Snapshot since all the Syntax are supported.
Please refer to https://manticore-projects.com/JSQLParser/usage.html#define-the-parser-features for activation of T-SQL Squared Bracket Quotation.

If you still face challenges, then please provide the specific query, shortened/simplified as much as possible.

**Comment by SconyHui** [comment]
Yes, I'm using version 4.6

**Comment by SconyHui** [comment]
eg：
	select [id],[name],[age] from [Student]
![image](https://user-images.githubusercontent.com/119842680/205585885-e1312190-8449-4dd0-8f3b-6d9b64ee631b.png)

**Comment by manticore-projects** [comment]
Please activate `SquaredBracket` Quotation.

**Comment by SconyHui** [comment]
Thank you. I'll try

**Comment by SconyHui** [comment]
Thank you. The question has been solved
But I also have problems using this syntax
![image](https://user-images.githubusercontent.com/119842680/205590851-15e00ff0-6245-4247-a307-810dd6b4cacf.png)

**Comment by manticore-projects** [comment]
[`SET @localVariable`](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/set-local-variable-transact-sql?view=sql-server-ver16)  is likely not supported.

You would either need to contribute a PR or sponsor the implementation.

**Comment by SconyHui** [comment]
I will apply to the company

**Comment by SconyHui** [comment]
Hi,
	Is the combination of BEGIIN END and IF not supported
![image](https://user-images.githubusercontent.com/119842680/205827051-7967e095-c6c9-4ea5-a7ec-f8c27b2c3ae5.png)

**Comment by manticore-projects** [comment]
Greetings.

Please refer to https://manticore-projects.com/JSQLParser/_static/JSqlParserCC.xhtml#Block

1) `Begin` `End` Blocks of statements are supported

2) `IF` `ELSE` Statements are supported

However, your example of  `IF` `ELSE` with `BLOCK`  is not supported.
It would depend on a major rewrite and/or refactoring since those constructs are MS SQL Server specific.

**Comment by SconyHui** [comment]
非常感谢，我找下其他方法解决此问题

**Comment by SconyHui** [comment]
Thank you very much. I will find another way to solve this problem

**Comment by manticore-projects** [comment]
I will provide a correction and improvement in the evening. On 6 Dec 2022 07:32, SconyHui ***@***.***> wrote:
Thank you very much. I will find another way to solve this problem

**Comment by wumpz** [comment]
@manticore-projects Did he sponsor the `set` improvement?

**Comment by manticore-projects** [comment]
> @manticore-projects Did he sponsor the `set` improvement?

No. :(
But I have to parse some MS SQL Server scripts for myself and so I did not mind.
