### ISSUE TITLE
MySQL format() not recognized

### ISSUE THREAD

**Issue by TearsOfJupiter** [JSQLParser/JSqlParser#1694]
The following MySQL will throw the following exception:

`select concat(format((30 / 100), 2), '%') as 'Thirty Percent'`

`Exception in thread "main" net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:65)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at Scratch.main(scratch_3.java:9)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 14.`

I tried the following:
`sql.replaceAll("format\\(", "round(")`
which worked because Oracle SQL doesn't have the `format()` function, apparently. but it does have the `round()` function. It would be nice if JSqlParser handled the MySQL `format()` function.

**Comment by manticore-projects** [comment]
Greetings,

please use a recent version of JSQLParser since [I can parse your statement with JSQLParser 4.6 Snapshot](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEkHsB2BjAhgFwBSwGIICcBbTHHAZgAZYB6WARkuoEoAaWAJljdgHIBSXt1gBBYHwwALAJYEMAT1gAHAKYEUKpBl4AoANxA)

**Comment by TearsOfJupiter** [comment]
Ah, perfect! That fixed it, thanks!
