### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by 1996-gjq** [JSQLParser/JSqlParser#1697]
java version 17.0
code:
```java
public static void main(String[] args) throws JSQLParserException {
    String sql = "SELECT  web_type,target,special,close,event_id,iphone_params,android_params,created_at,updated_at,modifier_user  FROM activity_popup";
    Select select = (Select) CCJSqlParserUtil.parse(sql);
  }
```

err:
```
Exception in thread "main" net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 32.

Was expecting one of:

    "&"
    "::"
    ";"
    "<<"
    ">>"
    "COLLATE"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "INTO"
    "START"
    "WINDOW"
    "["
    "^"
    "|"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:263)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47)
	at com.ayl.common.AndroidAppStore.main(AndroidAppStore.java:53)
```

this is bug?

**Comment by 1996-gjq** [comment]
<dependency>
    <groupId>com.github.jsqlparser</groupId>
    <artifactId>jsqlparser</artifactId>
    <version>4.5</version>
</dependency>

<dependency>
    <groupId>com.github.jsqlparser</groupId>
    <artifactId>jsqlparser</artifactId>
    <version>4.4</version>
</dependency>

**Comment by manticore-projects** [comment]
Greetings.

I can not re-produce your issue with JSQLParser 4.6 Snapshot. (You can try it online here.)[http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsHcCmAjA+gFwJ4AckCh4iiAaWDAQwCcBzJDQ402AZzwGMBLCgG0adhl2PAPYsCA+GSQA3JADsMaTgBN+TMpxwALEfKRoc1CgFsW64mQryVVEasPGzF5uypIKGJCrSeXU2ABXHBVPb18GSUFYExEVTgAzTiQqNEDxKnwAMQAlAHkAWVgKdgxOGU5sQxEcYPwAbiA]

It is possible, that an older version of JSQLParser detects `target`, `special` or `close` as a keyword. Although keyword management has been massively improved since. So please, use latest Snapshot.

**Comment by manticore-projects** [comment]
Closed as answered and solved.
