### ISSUE TITLE
Exception parsing show statement

### ISSUE THREAD

**Issue by jayant-kumar-yadav** [JSQLParser/JSqlParser#1702]
I am trying to parse "show indexes from my_table" and it is throwing ParseException :

net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "from" "FROM"
    at line 1, column 14.

Was expecting one of:

    ";"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:31234)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:31067)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:163)

**Comment by manticore-projects** [comment]
Greetings.

Your syntax show indexes from my_table is not supported, since it does not apply to any SQL Standard or major RDBMS (as far as I know).

[Supported syntax are shown here.](https://www.manticore-projects.com/JSQLParser/syntax.html)

You may want to provide or sponsor an implementation of this unsupported feature.

Please don't cross-post though.

**Comment by jayant-kumar-yadav** [comment]
MySql family DBs support this so I thought it would be there.

**Comment by manticore-projects** [comment]
Let me put it like this: We are mostly interested in parsing and understanding the actual logic of a SQL statement in order to find out about tables, columns, expressions, joins, where clauses etc.

Your statement does not yield any of such information (except maybe the table name). It is RDBMS specific syntax for analysis.

For that reason, it is not implemented yet. Nobody has had an interest so far, because its easier to just skip it.

However, you can provide a PR when this statement is important for you.

**Comment by jayant-kumar-yadav** [comment]
Added PR #1704

**Comment by manticore-projects** [comment]
Solved via commit [daa56ed](https://github.com/JSQLParser/JSqlParser/pull/1778/commits/daa56edb6ac6a4a4af6a6708a7e6d5c6d880def8) with PR #1778 

It does not make sense to implement all the various RDBMS specific syntax since the `SHOW` statement does not bear any value or interesting content. Although throwing exceptions is also annoying, so `UnsupportedStatement` is the way to go.

If you are really interested in the content of the `UnsupportedStatement` then please use Regular Expressions on it.

**Comment by manticore-projects** [comment]
Solved with PR #1704 and PR #1778
