### ISSUE TITLE
FOREIGN KEY syntax

### ISSUE THREAD

**Issue by Cr0s** [JSQLParser/JSqlParser#172]
Can you provide a BNF grammar for FOREIGN KEY syntax? I getting parser exception on this query:
```sql
CREATE TABLE IF NOT EXISTS table1 (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   aid INTEGER REFERENCES accounts ON aid ON DELETE CASCADE,
   name STRING,
   lastname STRING)
```

**Comment by wumpz** [comment]
The implementation is quite hacky. There are so many different constructs within create table. I will look into it. BTW I discovered a problem generating the java site which should generate a BNF like grammar using mavens JavaCC plugin.

**Comment by Cr0s** [comment]
Thanks! Can you also add ON UPDATE <ACTION>?
<ACTION> means CASCADE, SET NULL, RESTRICT

**Comment by Soben713** [comment]
I have the same problem.

**Comment by wumpz** [comment]
This should be solved. Which version do you use?

**Comment by Soben713** [comment]
I am using version 0.9.4, running 
`CCJSqlParserUtil.parse("CREATE TABLE SC(STID INT,COID INT,GRADE INT) FOREIGN KEY STID REFERENCES S ON DELETE CASCADE ON UPDATE CASCADE");` gives me `JSQLParserException`. It's probably irrelevant to this thread because I guess the exception is because of the foreign key option being outside the parenthesis but from what I know it's still a valid SQL statement.

**Comment by pabloa** [comment]
I fixed this. Now jsqlparser accepts on create update and on create delete. I do not see the git revision number though. Let me check if I uploaded this patch

**Comment by pabloa** [comment]
Yes, it is in this pull request: https://github.com/JSQLParser/JSqlParser/pull/210
