### ISSUE TITLE
[FEATURE] parsed Statements with comment

### ISSUE THREAD

**Issue by minskya** [JSQLParser/JSqlParser#1776]
### Grammar or Syntax Description
- when reading back from Validation.getParsedStatements it automatically removes any comments, i think we need to have a flag to leave as is.
- Example: `select * /*some comment*/ from a` --> currently only returns `select *  from a`

### Additional context
JSQLParser 4.6

**Comment by manticore-projects** [comment]
Greetings.

Unfortunately, this is correct: the Parser literally swallows any Comments as `SPECIAL_TOKENS` and removes them from the AST (simply as they do not belong to any Nodes of the AST).

If you want to keep the Comments, then I recommend to:
1) build a map of the comments based on the `ASCII Position` of occurance
2) parse and deparse your statement (could be a formatter too)
3) re-insert the comments based on the `ASCII Position` Map

You can check out JSQLFormatter, where I have done exactly this (since a Formatter definitely does not want to swallow comments).

https://github.com/manticore-projects/jsqlformatter/blob/e3bc912f3257f91ff5c880567ca0718ef4a6887a/src/main/java/com/manticore/jsqlformatter/JSQLFormatter.java#L1038
https://github.com/manticore-projects/jsqlformatter/blob/e3bc912f3257f91ff5c880567ca0718ef4a6887a/src/main/java/com/manticore/jsqlformatter/JSQLFormatter.java#L1102

**Comment by manticore-projects** [comment]
Closed, since I have explained it and no further questions has been asked since.
