### ISSUE TITLE
[BUG] JSQLParser Version 4.5: RDBMS : "Encountered unexpected token: "SELECT" <K_SELECT> at line 11, column 1."

### ISSUE THREAD

**Issue by paolinho91** [JSQLParser/JSqlParser#1798]
Always check against the **Latest SNAPSHOT of JSQLParser** and the [Syntax Diagram](https://jsqlparser.github.io/JSqlParser/syntax.html)

### Failing SQL Feature:
- Brief description of the failing SQL feature: method TablesNamesFinder.getTableList(statement) failed with error in title:
"Encountered unexpected token: "SELECT" <K_SELECT> at line 11, column 1"

### SQL Example:
- Simplified Query Example, focusing on the failing feature:
`
SELECT C1, 
	   SUM(N) AS N 
FROM 
(
	(
	SELECT C1,
		   SUM(N) AS N
	  FROM T1
  GROUP BY C1
	)
UNION ALL
	SELECT C1,
		   0 AS N
	  FROM T2
)
GROUP BY C1
`

### Software Information:
- JSqlParser version: 4.5
- Database: Oracle

### Tips:
Query is very bad but works on Oracle DB. Line 11 is the "UNION ALL" SQL command.

**Comment by manticore-projects** [comment]
Greetings!

This has been fixed in PR #1778 which will be released as JSQLParser 5 soonest.
[You can try it here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEsGMCMAoe70BpbAK4FsAKWAO1gEpYBBYUlAMQCUB5AWVmI-VAhnmTQYhwjNjxFSFarRKCR6Jm1gAXVPIwBxFgFUACrABCATURIKcodoByASWZXqYMBYw8ocUy-XxsABml08orsygBM5lrMeoYmAgDcQA)

**Comment by paolinho91** [comment]
many thanks! It works
