### ISSUE TITLE
[BUG] JSQLParser Version 4.6 : SQL Server : parsing takes too long

### ISSUE THREAD

**Issue by E1izabeth** [JSQLParser/JSqlParser#1800]
### Failing SQL Feature:
It takes too long to parse a query with multiple nested subqueries and/or joins with subqueries since 4.6
Can confirm, that 4.5 doesn't have this issue.

### SQL Example:

SELECT (SELECT '1.0' AS '@version', (SELECT 'Test' AS 'name', (SELECT (SELECT DISTINCT 51.64315 AS '@lat', 14.31709 AS '@lon' FOR XML PATH('trkpt'), TYPE) FOR XML PATH(''), ROOT('trkseg'), TYPE) FOR XML PATH('trk'), TYPE) FOR XML PATH('gpx'), TYPE) FOR XML PATH('')

Originally posted here https://github.com/dbeaver/dbeaver/issues/20060

### Software Information:
- JSqlParser 4.6
- MS SQL Server, but probably not only (we have an [issue about PostgreSQL](https://github.com/dbeaver/dbeaver/issues/20102) too, but without example)

**Comment by manticore-projects** [comment]
Greetings!

I will look into this and return with a solution soonest.

**Comment by manticore-projects** [comment]
@E1izabeth:

A first brief analysis reveals 2 challenges:

1) This particular clause `FOR XML PATH(...)` is not understood/supported by JSQLParser. Please [see the latest supported syntax here.](https://manticore-projects.com/JSQLParser/syntax_snapshot.html)

2) Despite that, of course, the Parser should not freeze, but time-out gracefully.
This happens at least with the latest Version JSQLParser 4.7 SNAPSHOT, [you can try it here online](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEAUoI1gcgIwDoAMrYEFg0ABANQFMAnAZwEsB7AO1QBoEko5VpzqAXPITSMAhgFtyrduE7TkcACIBJYNCUA5FAFYsANgAsAZnRaCRVMQA2IgW3T7MxgOzYAnGZKWmeAGIB5ACVYAA0AWTBYAAV8aAAJeFQ+SgBrAAcBAEo2aABNSJAM2H8gsIjouITULNgAvz9oBKTk6nIAcyrsvIKiwJDwqJj4xJSO2Fz8wuK+ssGE1tSAD1Hx7qnSgYrUKqA)

As you can see, parsing times out after 6 seconds (which is configurable as [explained here](https://manticore-projects.com/JSQLParser/usage.html#define-the-parser-features).

I will appreciate, if your team confirms from your end first, that latest Snapshot would time-out correctly with any given time-out period. (Otherwise I would need to help you getting the call implemented correctly).

In parallel, I would extend the grammar for support the clause.

**Comment by E1izabeth** [comment]
Thank you. I'll write you back, when I try snapshot.

**Comment by E1izabeth** [comment]
Confirm that 4.7 SNAPSHOT  doesn't have described issue with timeout on parse error. Thanks for your time!

Should change the title of the issue then as the main problem has been already solved?

**Comment by manticore-projects** [comment]
Thank you for the feedback!
Please leave it open so I can add support for the `FOR ...` clause (which seems to be Microsoft specific.

The 4.7 Snapshot will yield in Version 5.0 which is a major breaking release and you may want to run some tests before adoption. I will send your team a migration guide soonest.

In the meantime, a JSQLParser 4.6.1 may be needed with a back-port of this particular freezing fix. I will see what I can do about that.

**Comment by manticore-projects** [comment]
Greetings.

I have implemented the T_SQL `FOR ...` clause and [you can test it here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEAUsm1BGSDkBGAdABg1gEFhYMABANwFMAnAZwEsB7AOwwChlufekAaBCnBQ4ZaNXoAXQiTKsAhgFtqnPuo3rBiVKKHJd6ACIBJYNBMA5GF0137DngFZcANgAsAZixPipCgA2CjK2jmHhPIJY7jjeAOx4AJx+ZOQBbISwAGIA8gBKsAAaALJgsAAKRNAAEkIYUrQA1gAOMrAAlLCC0ACa5SAd2flFpRVVtYgYhJ2CeTk5cJMNjfTUAObTXbC9-YO5BSVllTV1y5vdfQOd+yNH43VrzQAe59uXe8OHYyeT0xwA3EA)

**Comment by E1izabeth** [comment]
Seems like it can be parsed now. Thank you!
