### ISSUE TITLE
Can ExpressionDeParser used within visit(CreateView createView)?

### ISSUE THREAD

**Issue by sisao** [JSQLParser/JSqlParser#182]
Hi is it possible to use the ExpressionDeParser not just with SelectDeParser?
Or did't I just find the docs?

Regards,
Stefan

```java
...
statement.accept(new StatementVisitor() {

    @Override
    public void visit(Select select) {
    	SelectDeParser deparser = new SelectDeParser(expressionDeParser, buffer);
    	expressionDeParser.setSelectVisitor(deparser);
    	expressionDeParser.setBuffer(buffer);
    	select.getSelectBody().accept(deparser);
    	System.out.println("select");
    }
                            
    @Override
    public void visit(CreateView createView) {
      //is it possible to use a ExpressionDeParser in here?
    }
}
```

**Comment by wumpz** [comment]
Not sure if I understand you. Do you ask because of `expressionDeParser.setSelectVisitor(deparser)`? This is needed for deparsing subselects within an exrpession. It has no effect on whatsoever deparser the ExpressionDeparser is started from. 
Mentioning this I discovered that the CreateViewDeparser indeed does not use a ExpressionDeparser but simple a `toString` to create the needed output.
What do you want to achieve? Simple output, maybe `toString` is enough?

But this code should work:

~~~
 @Override
    public void visit(CreateView createView) {
        SelectDeParser deparser = new SelectDeParser(expressionDeParser, buffer);
        expressionDeParser.setSelectVisitor(deparser);
        expressionDeParser.setBuffer(buffer);
        createView.getSelectBody().accept(deparser);
    }
~~~

**Comment by sisao** [comment]
Thx.

Maybe I'm on a wrong approach..
What I try to achive is to quote columns.

So I tried this:
´´´java
final ExpressionDeParser expressionDeParser = new ExpressionDeParser() {

@Override
public void visit(Column tableColumn) {
...
}

´´´

this is working for select statements but not for the create view...

2015-10-13 14:25 GMT+02:00 Tobias <notifications@github.com>:

**Comment by wumpz** [comment]
My simple example with your ExpressionDeParser should do it. Could you give more source code, more context? Maybe there is a problem somewhere else.

**Comment by sisao** [comment]
Your example works fine, but how do I get the changed buffer back into the
create view statement?

If I should use setSelectBody? How do I create a Body from a String?

2015-10-13 17:37 GMT+02:00 Tobias <notifications@github.com>:

**Comment by wumpz** [comment]
I modified the CreateViewDeparser to handle such problems. I included a test **CreateViewDeParserTest** where you could look how to do it. Actually there are two possibilities. The first to tackle the problem is the way you took. The second is a very new approach to JSqlParser. For some parts of the parsed sql there are AST tree nodes generated with string positions. Fortunatly column is one of these. One could roll through all columns and correct the original sql string.

Hope that helps and thx for using JSqlParser.
