### ISSUE TITLE
[BUG] JSQLParser Version : 4.7 parsed error 

### ISSUE THREAD

**Issue by tdelain** [JSQLParser/JSqlParser#1884]
SELECT ID FROM a6_ WHERE opIn & 0x1603ffff823 = 0x1603ffff820  AND date>='20131208_233900'

Cannot be parsed. It was working well with v1.1

net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "ND" <S_IDENTIFIER>
    at line 1, column 64.

Was expecting one of:

    "::"
    "["
    "^"
    <EOF>
    <ST_SEMICOLON>

	at net.sf.jsqlparser.parser.CCJSqlParserManager.parse(CCJSqlParserManager.java:25)

With parentheses, it is OK :
SELECT ID FROM a6_ WHERE (opIn & 0x1603ffff823 = 0x1603ffff820)  AND date>='20131208_233900'

### Software Information:
- JSqlParser version 4.7
- Database : no database, just parse

**Comment by manticore-projects** [comment]
Greetings.

Thank you for reporting. If you add brackets, it will work:
```sql
SELECT id
FROM a6_
WHERE ( opin & 0x1603ffff823  = 0x1603ffff820 )
    AND date >= '20131208_233900'
;
```

[You can try it online here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAECWATAUAMQEoHkCysCGAbAPrIDqAEiOiLABSwD2ADvAHawBksADAB4CMBbgGYAZuNEAOAEzDYsALw8BQsRJndYASmTz5AQQByAEViI8AFwCmsAHxKA5NO79h-Z5KKzhATm7cHZABuIA)

There were many new Operators adopted since JSQLParser 1 and so the BitAnd may be misread.
Patches are welcome, I don't have much time to investigate this right now.

**Comment by manticore-projects** [comment]
Actually it works with JSQLParser 4.8 Snapshot.
[Please try it here.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAECWATAUAMQEoHkCysCGAbAPrIDqAEiOiLAPYAO8AdrAGSwAMAHgIwEcBmAGYihADgBMA2DIC8nXv2GjJHZDJkBBAHIARWIjwAXAKawAfPIDkEjjwE9bYolIEBODhyvIA3EA)

![image](https://github.com/JSQLParser/JSqlParser/assets/18080123/ed3b57bc-1d7a-4081-88bb-6395c1cd4af5)

**Comment by manticore-projects** [comment]
Closing this since its working and no further question has been asked.
