### ISSUE TITLE
[FEATURE] Mention jOOQ as another alternative in the README

### ISSUE THREAD

**Issue by lukaseder** [JSQLParser/JSqlParser#1968]
I've noticed that you're mentioning [General SQL Parser](http://www.sqlparser.com/features/introduce.php?utm_source=github-jsqlparser&utm_medium=text-general) in your `README.md`:

- https://github.com/JSQLParser/JSqlParser/blob/master/README.md

Would it be worth mentioning jOOQ's parser as well?

- https://www.jooq.org/doc/latest/manual/sql-building/sql-parser/
- https://www.jooq.org/translate/

It supports a lot of RDBMS, translation between dialects, SQL transformation, can be used as a JDBC proxy for translation and transformation purposes, etc. and is dual-licensed

**Comment by manticore-projects** [comment]
Greetings Lukas, always good to here from you.

Sure we should do that, would you like to mention us as well? (E. g. as a "Generated Parser Alternative").

**Comment by lukaseder** [comment]
Thanks, @manticore-projects. I had thought about it, but I wouldn't know where to put it. jOOQ doesn't have such a section of "alternatives," specifically because the parser isn't really jOOQ's most popular feature. I've recommended JSqlParser a few times to customers, though, especially if a different license was a requirement.

**Comment by manticore-projects** [comment]
All good. We will see at the usual placed. Cheers On 19 Feb 2024 19:26, Lukas Eder ***@***.***> wrote:
Thanks, @manticore-projects. I had thought about it, but I wouldn't know where to put it. jOOQ doesn't have such a section of "alternatives," specifically because the parser isn't really jOOQ's most popular feature. I've recommended JSqlParser a few times to customers, though, especially if a different license was a requirement.
