### ISSUE TITLE
This is really a release update request

### ISSUE THREAD

**Issue by dabayliss** [JSQLParser/JSqlParser#1974]
4.8 in Maven has a transitive vulnerability (on h2)

![image](https://github.com/JSQLParser/JSqlParser/assets/954376/68100667-20d5-4abc-9940-4e24c80b9c0e)

is it possible to get a release without the vulnerability ?

**Comment by manticore-projects** [comment]
Greetings!

Thank you for reporting. We will definitely update, but not immediately because:
1) H2 is only a test dependency and not part of the JSQLParser package
2) H2-2.2.224 depends on JDK 11 while we still maintain JDK 8 compatibility

We are discussing right now how/when to raise compatibility to JDK 11.

**Comment by manticore-projects** [comment]
Greetings.

@wumpz just has released 4.9 as last JDK8 compatible version.
Snapshot 4.10 has been updated to JDK11 including Test dependency to H2 2.2.224.
