### ISSUE TITLE
[FEATURE] `getTable` method of `Column` with full context

### ISSUE THREAD

**Issue by arodriguezdlc** [JSQLParser/JSqlParser#2042]
### Description

As indicated at the docstrings, the `getTable` method from `Column` object only returns the table name if it is in the local context. I will copy the docstring here:

```
The inference is based only on local information, and not on the whole SQL command. For example, consider the following query:
   SELECT x FROM Foo
Given the Column called x, this method would return null, and not the info about the table Foo. On the other hand, consider:
   SELECT t. x FROM Foo t
Here, we will get a Table object for a table called t. But because the inference is local, such object will not know that t is just an alias for Foo.
```

It would be possible to have the full context of the FromItem related to the Column??

### Additional context
I would like to transform the SQL using a custom deparser, but I need to know if the Column I'm transforming comes from a table (and which table) or comes from another expression, like a subquery.

**Comment by manticore-projects** [comment]
Greetings.

Unfortunately I do not fully understand what you are looking for. I assume its about full Column Resolution and Lineage.
If I am correct then this can't be done by JSQLParser alone since it depends in Schema information. The good news is that I just finished work on a sister project: [JSQLTranspiler](https://manticore-projects.com/JSQLTranspiler/resolve.html), which gives you the full lineage and points on the physical column. 

Please have a look at the shown examples and let me know if this solves you challenge.
Otherwise please feel welcome to illustrate further your requirements -- best case with simple input and expected output examples.

**Comment by manticore-projects** [comment]
For your given example:

```sql
SELECT t. x FROM Foo t
```

JSQLTranspiler would resolve the column like this:
```
t.x --> Foo.x
``

and for the more generic example

```sql
SELECT * FROM Foo t
```

JSQLTranspiler would resolve all the columns of `Foo` like this:
```
t.x --> Foo.x
t.col2 --> Foo.col2
...
t.col10 -- > Foo.col10
``

(depending on the actual columns held in physical table `Foo`.

**Comment by manticore-projects** [comment]
Is this still relevant? Otherwise I would close this issue.
