### ISSUE TITLE
[BUG] JSQLParser Version 5.0 : RDBMS : failing parsing empty statements with ;

### ISSUE THREAD

**Issue by d2a-raudenaerde** [JSQLParser/JSqlParser#2063]
### Failing SQL Feature:
- Parsing multiple empty  statements fails

### SQL Example:
- Simplified Query Example, focusing on the failing feature
    ```sql
    -- Just commented out 
    /* 
     */
    ;
    ```

### Software Information:
- JSqlParser version 5.0

This works fine in Postgres

**Comment by manticore-projects** [comment]
Greetings!

this is a known issue which does not have a good solution because: What `statement` would you want the parser to return here?
Instead, apply a SQL Comment filter (e.g. using a regex) and check remaining length before sending to the parser.

**Comment by d2a-raudenaerde** [comment]
Well, I expect an empty list as I am parsing multiple statements :)

(alternatively, EmptyStatement would be ok-isch)

**Comment by manticore-projects** [comment]
> Well, I expect an empty list as I am parsing multiple statements :)
> 
> (alternatively, EmptyStatement would be ok-isch)

I get your point and before actually working on the parser I would have done the same.
However, the Parser Generator is not easily supporting this because there is only "IF MATCH" but no "ELSE".

If you can make it work, your PR will be most welcome.
I myself find it easier to mangle the the statements before with Regular expressions.
