### ISSUE TITLE
[BUG] JSQLParser Version : TableNamesFinder failing in 5.1-SNAPSHOT version

### ISSUE THREAD

**Issue by arodriguezdlc** [JSQLParser/JSqlParser#2085]
We have some test to ensure that TableNamesFinder finds all tables correctly. Until version 4.9, it worked well, but with 5.1-SNAPSHOT, we have find a case which is not working properly.

Given the query: 

SELECT * FROM (SELECT * FROM A) AS A JOIN B ON A.a = B.a JOIN C ON A.a = C.a 

TableNamesFinder should find tables A, B and C, but only B, C were found. 

We have seen that there is a drop of tables if they are alias, may be here its detecting the alias A like a table to remove when it shouldn't. 

### Software Information:
- JSqlParser version: 5.1-SNAPSHOT

**Comment by manticore-projects** [comment]
Greetings!

Thank you for reporting, however this is a feature and not a bug. Let me explain:

1) for a reliable table name resolution you will need Schema information. You can use JSQLTranspiler to achieve that because JSQLTranspiler is aware of naming scopes.

2) for your given example, indeed the Alias overwrites the table because (without schema information) we can never be sure if "A" is indeed a table. Example

```sql
with as as (select 1)
select * from a
```

What is the table here? Previous the improvement, "a" was returned as a table.

3) You can use the extended method `getTablesOrOtherSources` if you want to get the 'a' for both examples above.

**Comment by oscarbonilla-tid** [comment]
Thanks for the explanation. We'll give it a try with getTablesOrOtherSources
