### ISSUE TITLE
[BUG] JSQLParser Version : RDBMS : failing feature description

### ISSUE THREAD

**Issue by tiboun** [JSQLParser/JSqlParser#2093]
### Failing SQL Feature:
- Parsing table name with bigquery syntax may fail for names with -
- `select * from my-project.dataset.table` fail. But if we quote it as an identifier it works. **select * from \`my-project.dataset.table\`**.

![image](https://github.com/user-attachments/assets/4967d6d7-eb0f-4bba-b72d-22cdc4da3502)

Do you think we can manage this or should we quote table's name with identifier ?

**Comment by manticore-projects** [comment]
Greetings!

Thank you for reporting, but the Dash `-` in the Catalog name needs to be quoted, Similar rules for identifiers apply to every other programming language, like Java or C.

So the following will work:
```sql
select * from myproject.dataset.table;
select * from my_project.dataset.table;
select * from `my-project`.dataset.table;
select * from `my-project.dataset.table`;
```

**Comment by tiboun** [comment]
Thanks @manticore-projects , I agree that this character should be escaped but the query itself is valid in bigquery. If it's too specific, then we will quote them :)

**Comment by manticore-projects** [comment]
Yes, I understand that, But especially the dash/minus is tricky because it can be an Operator.

```sql
select my-project.dataset.table
```

is valid SQL, but would read it is difference between "my" and "project.dataset.table".
It's always a trade off between the speed of the parser and complexity to introduce. So unless we want to die on this hill, it's a won't fix. What do you think?

**Comment by tiboun** [comment]
No problem, we can manage on our side.
