### ISSUE TITLE
CCJSqlParserUtil fails to parse statement separated by ';'

### ISSUE THREAD

**Issue by peterlitvak** [JSQLParser/JSqlParser#337]
Maybe this works as designed but but the following fails with exception:
```
CCJSqlParserUtil.parse("UPDATE a SET x = 1;\nUPDATE b SET z = 2;")
```

```
Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "UPDATE" "UPDATE "" at line 2, column 1.
Was expecting:
    <EOF>
```

**Comment by wumpz** [comment]
You have a script. Therefore use parseStatements.

-------- Ursprüngliche Nachricht --------
Von: Peter Litvak <notifications@github.com> 
Datum: 13.09.2016  03:36  (GMT+01:00) 
An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> 
Betreff: [JSQLParser/JSqlParser] CCJSqlParserUtil fails to parse statement
  separated by ';' (#337) 

Maybe this works as designed but but the following fails with exception:

CCJSqlParserUtil.parse("UPDATE a SET x = 1;\nUPDATE b SET z = 2;")


Caused by:
net.sf.jsqlparser.parser.ParseException: Encountered " "UPDATE" "UPDATE "" at line 2, column 1.
Was expecting:
    <EOF>


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JSQLParser/JSqlParser","title":"JSQLParser/JSqlParser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JSQLParser/JSqlParser"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"CCJSqlParserUtil fails to parse statement separated by ';' (#337)"}],"action":{"name":"View Issue","url":"https://github.com/JSQLParser/JSqlParser/issues/337"}}}

**Comment by peterlitvak** [comment]
Thank you
