### ISSUE TITLE
Self join clause is passing which is supposed to fail

### ISSUE THREAD

**Issue by raveendra18** [JSQLParser/JSqlParser#347]
Hi,
I am using your library and its amazing. We are facing an issue in the following use case. For eg if a query comes like this to the system,

select o1.offerId, o1.brandId, o2.salePrice From offers o1, offers where o1.mpid = o2.mpid is not throwing error.

Since there is no alias o2, it should throw error in the FROM clause and in the WHERE clause as well for  using alias o2 which isn't defined. 

Also i would love to know if there is  a way to extend the Visitor pattern to support a generic return type ?

Thanks in advance,
raveendra

**Comment by wumpz** [comment]
No its not. JSqlParser is a **parser**.  It does no sematical checking after an sql was parsed. This is up to you ;). 
Nevertheless one could implement a visitor to validate an sql regarding some constraints, e.g. used tables or aliases have to be in the from part, ... But there are some heavy limitations to this, due to JSqlParser does not know about a specific database schema. If you have one, then also some not available columns could be found
`select not_existing_column from mytable`

**Comment by wumpz** [comment]
Sorry. I overlooked the second part of your question. I am not sure what you mean by generics within visitors.  Could you give an example?
