### ISSUE TITLE
IN and NOT IN not working

### ISSUE THREAD

**Issue by afariha** [JSQLParser/JSqlParser#379]
```
Exception in thread "main" java.lang.NullPointerException
	at net.sf.jsqlparser.statement.select.PlainSelect.accept(PlainSelect.java:134)
```

Query was

`select rank from DBObjects where rank NOT IN (0,1)`

and

`select rank from DBObjects where rank IN (0,1)`

**Comment by wumpz** [comment]
Both statements are parsed perfectly well. So your problem seems to be somewhere else. 

Ah I see. You are using a visitor to traverse these statements. The only way 
`selectVisitor.visit(this);`
is going to throw a NPE is when selectVisitor is null. Therefore I assume there is a problem within the initialization of your visitor implementation.

**Comment by afariha** [comment]
Thanks. I will look into this.

**Comment by wumpz** [comment]
Can we close this one ?

**Comment by afariha** [comment]
Yes sure!
