### ISSUE TITLE
BIGINT constants support

### ISSUE THREAD

**Issue by serge-rider** [JSQLParser/JSqlParser#390]
Parser fails with when SQL expression contains long BIGINT constant.
Example:
```sql
select * from student where student_no = 20161114000000035001;
```
Error:
```
java.lang.NumberFormatException: Passed value does not contain a parsable long value
```
I see that net.sf.jsqlparser.expression.LongValue keeps value as `long`. Maybe it should be BigInteger. Or maybe BigIntegerValue expression should be introduced.

Source problem: https://github.com/serge-rider/dbeaver/issues/1116

**Comment by wumpz** [comment]
Hope that helps. I did not yet published the compiled version. 

The LongValue now accepts all numbers regarding the grammar definition. 
`< S_LONG: ( <DIGIT> )+ >`
So veeerrry large numbers are allowed. 

Only if one wants the long value using getValue, the Long.valueOf call will fail. I introduced another getBigInteger method to handle larger values.

**Comment by serge-rider** [comment]
Great, thanks!

**Comment by wumpz** [comment]
I am a fan of dbeaver. Thx  for using JSqlParser. Tobias

Am 1. Februar 2017, um 17:55, schrieb Serge Rider <notifications@github.com>:

Great, thanks!

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JSQLParser/JSqlParser","title":"JSQLParser/JSqlParser","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/JSQLParser/JSqlParser">https://github.com/JSQLParser/JSqlParser</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@serge-rider in #390: Great, thanks!"}],"action":{"name":"View Issue","url":"<a href="https://github.com/JSQLParser/JSqlParser/issues/390#issuecomment-276713418">https://github.com/JSQLParser/JSqlParser/issues/390#issuecomment-276713418</a>"}}}
