### ISSUE TITLE
The PayPal donate button seems broken

### ISSUE THREAD

**Issue by ftomassetti** [JSQLParser/JSqlParser#448]
This is how I see it

![screen shot 2017-05-14 at 11 32 25](https://cloud.githubusercontent.com/assets/439078/26032665/0f375ac2-3899-11e7-9a3f-df7b11fa6284.png)

**Comment by wumpz** [comment]
Thx for the info.

-------- Ursprüngliche Nachricht --------
Von: Federico Tomassetti <notifications@github.com> 
Datum: 14.05.2017  11:32  (GMT+01:00) 
An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Betreff: [JSQLParser/JSqlParser] The PayPal donate button seems broken (#448) 

This is how I see it


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JSQLParser/JSqlParser","title":"JSQLParser/JSqlParser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JSQLParser/JSqlParser"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"The PayPal donate button seems broken (#448)"}],"action":{"name":"View Issue","url":"https://github.com/JSQLParser/JSqlParser/issues/448"}}}
