### ISSUE TITLE
Parse support for PostgreSQL show run-time parameter

### ISSUE THREAD

**Issue by gdfbarbosa** [JSQLParser/JSqlParser#450]
Hello,

I`m working on a project which needs to parse several PostgreSQL specific queries, and among them we need to parse Set statements and Show statements.
But it seems the actual version of the grammar does not support show statements in the form:

show variable;
show all;

Is this grammar support expected to enter in the next release?
Would you accept a pull request for this if needed?

**Comment by wumpz** [comment]
PR would be wellcome. As you may know souce code conventions are tested while building.

**Comment by eolivelli** [comment]
+1 this would be very useful for me too

**Comment by ormera** [comment]
Tested in version 2.0 and still seems to be an open issue

### Actual Behavior
Exception parsing Postgresl SQL "show transaction_isolation" or "show DateStyle"

 net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "transaction_isolation" <S_IDENTIFIER>
    at line 1, column 6.

Was expecting:

    "COLUMNS"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20872)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Show(CCJSqlParser.java:667)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:189)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:70)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:36)
	at com.gs.qubits.calcite.demos.SqlParser.main(SqlParser.java:44)

### Expected Behavior
Expected to parse to a statement
https://www.postgresql.org/docs/11/sql-show.html


### Steps to Reproduce the Problem

```java
String sql = "show transaction_isolation";
Statement expr = CCJSqlParserUtil.parse(sql);
```


### Specifications

  - Version: 1.4 & 2.0

**Comment by wumpz** [comment]
Long living issue finally fixed. Could you check it? I deployed the actual snapshot.

**Comment by ormera** [comment]
Thanks, appreciate the quick fix (from when I hit the issue).  I just tested from master and it resolved the issue I was seeing.
