### ISSUE TITLE
not support mysql comment #

### ISSUE THREAD

**Issue by packageOk** [JSQLParser/JSqlParser#454]
when a sql contains comment like '#', jsqlParser will throw a exception. here is code
> public void test4() throws JSQLParserException {
        String sql = "SELECT * FROM `table1` WHERE `name` LIKE '%#%' # here is a comment";
        Select select = (Select) CCJSqlParserUtil.parse(sql);
        System.out.println(select);
    }

here is exception
> net.sf.jsqlparser.parser.TokenMgrError: Lexical error at line 1, column 49.  Encountered: " " (32), after : "#"
	at net.sf.jsqlparser.parser.CCJSqlParserTokenManager.getNextToken(CCJSqlParserTokenManager.java:3087)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_scan_token(CCJSqlParser.java:16258)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_3R_471(CCJSqlParser.java:14225)

I had thougth about removing all characters after '#', but I worry that character '#' is a part of statement just like my code. Anyone can help me?

**Comment by wumpz** [comment]
JSqlParser does only support /* .. */ and -- comments. These are sql standard complient. I am afraid to collide with some other json syntax constructs. So an imlementation will at the moment not be there.

**Comment by packageOk** [comment]
collide with some other json syntax constructs? I don't understand.
Does it difficult to add the support? if not, I will try.

**Comment by wumpz** [comment]
Postgresql has some operators regarding json processing like #>. Anyway, have a try. PRs are wellcome.

**Comment by packageOk** [comment]
I remove #> ,because I use mysql not postgresql. I think it is not suit for JsqlParser, so I don't pull a request.
Another question, how about supporting Show Syntax like "show tables" or "show create table"?

**Comment by wumpz** [comment]
Should not be a problem. Could you file an issue?

-------- Ursprüngliche Nachricht --------
Von: packageOk <notifications@github.com> 
Datum: 02.06.2017  11:55  (GMT+01:00) 
An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> 
Cc: Tobias <t.warneke@gmx.net>, Comment <comment@noreply.github.com> 
Betreff: Re: [JSQLParser/JSqlParser] not support mysql comment # (#454) 

I remove #> ,because I use mysql not postgresql. I think it is not suit for JsqlParser, so I don't pull a request.

Another question, how about supporting Show Syntax like "show tables" or "show create table"?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JSQLParser/JSqlParser","title":"JSQLParser/JSqlParser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JSQLParser/JSqlParser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@packageOk in #454: I remove #\u003e ,because I use mysql not postgresql. I think it is not suit for JsqlParser, so I don't pull a request.\r\nAnother question, how about supporting Show Syntax like \"show tables\" or \"show create table\"?"}],"action":{"name":"View Issue","url":"https://github.com/JSQLParser/JSqlParser/issues/454#issuecomment-305743544"}}}
