### ISSUE TITLE
Table's getFullyQualifiedName method doesn't work correctly

### ISSUE THREAD

**Issue by shu22203** [JSQLParser/JSqlParser#458]
when creating new Table object with Database name and executing getFullyQualifiedName() method, this method returns an incorrect result that has two dots between databaseName and tableName. here is code.

```Java
Table tb = new Table("tableName");
tb.setDatabase(new Database("dbName"));
System.out.println(tb.getFullyQualifiedName());

=> tableName..dbName
```
if this is a bug, I will fix and send a pull request.

**Comment by wumpz** [comment]
Using SqlServer the is imho valid.

-------- Ursprüngliche Nachricht --------
Von: Shu Murakami <notifications@github.com> 
Datum: 04.06.2017  08:40  (GMT+01:00) 
An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Betreff: [JSQLParser/JSqlParser] Table's getFullyQualifiedName method doesn't
  work correctly (#458) 

when creating new Table object with Database name and executing getFullyQualifiedName() method, this method returns an incorrect result that has two dots between databaseName and tableName. here is code.
Table tb = new Table("tableName");
tb.setDatabase(new Database("dbName"));
System.out.println(tb.getFullyQualifiedName());

=> tableName..dbName
if this is a bug, I will fix and send a pull request.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JSQLParser/JSqlParser","title":"JSQLParser/JSqlParser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JSQLParser/JSqlParser"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Table's getFullyQualifiedName method doesn't work correctly (#458)"}],"action":{"name":"View Issue","url":"https://github.com/JSQLParser/JSqlParser/issues/458"}}}

**Comment by shu22203** [comment]
That seems correct. I am using MySQL, that's what is causing the problem. Sorry for the misunderstanding.
