### ISSUE TITLE
Parsing constant value fields

### ISSUE THREAD

**Issue by yakclock** [JSQLParser/JSqlParser#500]
Hello , I have a use case where I need to parse SELECT statements like:
```sql
SELECT '' as foo, name FROM TABLE_A
```
  or
```sql
SELECT 'foo' as x, name FROM TABLE_A
```

  But the following code will skip visiting the 'x' column and only return 'y' . Should JSqlParser be able to handle this type of statement ?

Thanks.

```java
@Test
public void getColumnNames_ConstantAlias() throws Exception {
	List<String> list = getColumnNamesVisit("SELECT 'foo' as x, y  FROM DUAL");
	Assert.assertEquals(2, list.size());
	Assert.assertEquals("x", list.get(0));
	Assert.assertEquals("y", list.get(1));
}
	
public List<String> getColumnNamesVisit(String sqlStatement) throws Exception {
	final List<String> columnNames = new LinkedList<String>();
	SimpleNode node = (SimpleNode) CCJSqlParserUtil.parseAST(sqlStatement);
	node.jjtAccept(new CCJSqlParserDefaultVisitor() {

	@Override
	public Object visit(SimpleNode node, Object data) {
		if(node.jjtGetValue()!=null&&node.jjtGetValue() instanceof Column) {
			String colName = ((Column)node.jjtGetValue()).getColumnName();
			System.out.println(colName);
			columnNames.add(colName);
		}
		return super.visit(node, data);
	}
	
}, null);
		return columnNames;
	}
```

**Comment by wumpz** [comment]
The problem here is that the first is not a **column** but a **string value** object. Due to the heavy performance impact JSqlParser does not produce AST nodes for every production, but I see no problem in introducing a node for a SelectExpressionItem. Then you could get your "columns" there.

So the statement is parseable but the way you want to process it is not provided for your usecase. Are you aware that the columns AST - nodes are not limited to the selected items and you will get also column objects from e.g. the where clause.

**Comment by yakclock** [comment]
Thank you, I will give that a try. I wasn't aware columns are also provided from the where clause but the particular problem I'm facing at the moment means I'm trying to parse thousands of immutable sql statements similar to my example and having the columns in the same order as they appear in the select is critical.

Great library by the way.

**Comment by wumpz** [comment]
Then going for columns is the wrong way. Even the AST node try does not fit your problem. You should access your statement directly and look into the selected items list. 
Or do I miss understand your problem?  Do you need the alias names or indeed columns? What if the selection returns an expression like cold + col2 as myname?
