### ISSUE TITLE
Unable to parse function with multiple expression values

### ISSUE THREAD

**Issue by riteshtijoriwala** [JSQLParser/JSqlParser#503]
The following parses correctly:
1. select foo(a.b);
2. select foo(a.b, 5);

The following does not parse:
1. select foo(a.b, a.x);

Should this work? Any help appreciated. Thanks!

**Comment by wumpz** [comment]
I guess it should work. Seems like a bug.
Tobias

-------- Ursprüngliche Nachricht --------
Von: riteshtijoriwala <notifications@github.com> 
Datum: 27.08.2017  00:13  (GMT+01:00) 
An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Betreff: [JSQLParser/JSqlParser] Unable to parse function with multiple
  expression values (#503) 

The following parses correctly:

select foo(a.b);
select foo(a.b, 5);

The following does not parse:

select foo(a.b, a.x);

Should this work? Any help appreciated. Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JSQLParser/JSqlParser","title":"JSQLParser/JSqlParser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JSQLParser/JSqlParser"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Unable to parse function with multiple expression values (#503)"}],"action":{"name":"View Issue","url":"https://github.com/JSQLParser/JSqlParser/issues/503"}}}

**Comment by riteshtijoriwala** [comment]
Any suggestions on fixing it? I am just starting to browse the codebase.

**Comment by riteshtijoriwala** [comment]
This also doesn't seem to work:

2. select foo(a.b, bar(x.y)) as X

**Comment by AnEmortalKid** [comment]
@riteshtijoriwala set the debug mode on (so you can view what token the grammar is trying to tie it to). Maybe there's a rule for `a.x` that isn't `0 or many`

**Comment by riteshtijoriwala** [comment]
Thank you @AnEmortalKid , @wumpz . There was some issue in escaping the input SQL string. The mentioned use cases work perfectly now!

**Comment by wumpz** [comment]
So I will close this. ...
