### ISSUE TITLE
delete parser ERROR，can't get tableName

### ISSUE THREAD

**Issue by liubin0821** [JSQLParser/JSqlParser#523]
Hi : 
i used JSqlParser - version 1.1
for example:

//-------------- code ---------------
//oracle
String delSql2 = "delete from a  a where exists (select 1 from b b where a.id5=b.id3)";
//mysql or db2
String delSql3 = "DELETE FROM TBM_INCOME WHERE id=2";

 Delete delete = (Delete) CCJSqlParserUtil.parse(sql);

System.out.println("delete tables : "+delete.getTables());
//-------------- code end ---------------

all output is empty....but select or update is correct...
pls help...thx .....

**Comment by wumpz** [comment]
Hi, getTables is only used for multi  table deletes like "delete tab1 tab2 from ...". You need to use getTable and getJoins. What do you want to achieve? Tablelist  from sql? Cheers Tobias 

-------- Ursprüngliche Nachricht --------
Von: liubin0821 <notifications@github.com> 
Datum: 14.10.2017  10:36  (GMT+01:00) 
An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Betreff: [JSQLParser/JSqlParser] delete parser ERROR，can't get tableName (#523) 

Hi :

i used JSqlParser - version 1.1

for example:
//-------------- code ---------------

//oracle

String delSql2 = "delete from a  a where exists (select 1 from b b where a.id5=b.id3)";

//mysql or db2

String delSql3 = "DELETE FROM TBM_INCOME WHERE id=2";
Delete delete = (Delete) CCJSqlParserUtil.parse(sql);
System.out.println("delete tables : "+delete.getTables());

//-------------- code end ---------------
all output is empty....but select or update is correct...

pls help...thx .....

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JSQLParser/JSqlParser","title":"JSQLParser/JSqlParser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JSQLParser/JSqlParser"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"delete parser ERROR，can't get tableName (#523)"}],"action":{"name":"View Issue","url":"https://github.com/JSQLParser/JSqlParser/issues/523"}}}​​

**Comment by wumpz** [comment]
Did this hint help you? Can we close this problem?
