### ISSUE TITLE
How to run the parser

### ISSUE THREAD

**Issue by tianchao-haohan** [JSQLParser/JSqlParser#552]
Could you please tell me how to run the parser on "src/test/resources/simple_parsing.txt"?
I want to see the parse result withe JSqlParser on those samples.

**Comment by wumpz** [comment]
Look at net.sf.jsqlparser.test.simpleparsing.CCJSqlParserManagerTest. 
But this parser check is the "old" way to do it. I prefer to check each with a parse and deparse. But that is more or less a matter of taste. 

Why do you want to explicitly parse the statements from this file?

**Comment by tianchao-haohan** [comment]
@wumpz 
Thanks. What I want is a just a tool that could be run standalone. The input is a given sql and the output is the parse result by JSqlParser.
For example, 
./JSqlParser input_file  (or java -jar JSqlParser.jar input_file)
input_file contains the sql statement:  SELECT col1, col2 FROM mytable WHERE id = 1234
And the output: SELECT col1, col2 FROM mytable WHERE id = ?

**Comment by wumpz** [comment]
Are you asking for a method that:
1. opens a file
2. reads in all data of that file
3. parse using CCJSqlParserUtil.parseStatements
4. output to System.out
???
I am asking, because its so straight forward to implement and only point 3 is JSqlParser specific.

Again, follow the CCJSqlParserManagerTest and output the parseresults using .toString() of the parse objects.

**Comment by tianchao-haohan** [comment]
@wumpz got it, thanks!
