### ISSUE TITLE
Join ON fails to parse from Oracle

### ISSUE THREAD

**Issue by dondank** [JSQLParser/JSqlParser#596]
the following does not parse:

`SELECT * FROM a JOIN b JOIN c ON b.id = c.id ON a.id = c.id`

It is legal in Oracle. 
Parsing fails on master.

following one succeeds:
`SELECT * FROM a JOIN (b JOIN c ON b.id = c.id) ON a.id = c.id`

**Comment by wumpz** [comment]
This join construct is not (yet) implemented.
-------- Ursprüngliche Nachricht --------Von: dondank <notifications@github.com> Datum: 26.03.18  12:56  (GMT+01:00) An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [JSQLParser/JSqlParser] Join ON fails to parse from Oracle (#596) 
the following does not parse:
SELECT * FROM a JOIN b JOIN c ON b.id = c.id ON a.id = c.id
It is legal in Oracle.

Parsing fails on master.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JSQLParser/JSqlParser","title":"JSQLParser/JSqlParser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JSQLParser/JSqlParser"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Join ON fails to parse from Oracle (#596)"}],"action":{"name":"View Issue","url":"https://github.com/JSQLParser/JSqlParser/issues/596"}}}

**Comment by dondank** [comment]
is this planned? JOIN-ON  is very common in most databases.
Thanks.

**Comment by wumpz** [comment]
Let me take a look. If parenthesis parsing succeeds it should not be that hard. Cheers Tobias

**Comment by wumpz** [comment]
This would introduce a circular production hell. Its not so easy as I thought. Sorry.

**Comment by cesarochoa2006** [comment]
There are any plans to support it? I have a lot of cases with queries that have it.

**Comment by manticore-projects** [comment]
[Works with JSQLParser-4.2](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEBUAoAYgJQPIFlYENGwNgCl0BJAOVgCN9CSLYBjWww9SqgOgEsATWALxMevFq1jtcIwcL6IA3EA+)
