### ISSUE TITLE
Unrecognized function REGEXP

### ISSUE THREAD

**Issue by coderstory** [JSQLParser/JSqlParser#621]
SELECT CASE WHEN '0' IN (SELECT CASE WHEN `archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E`.`f_161D0A31-C361-CFC9-3F43-5738DEDE148B` = '' THEN '1' ELSE `archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E`.`f_161D0A31-C361-CFC9-3F43-5738DEDE148B` REGEXP '^[\\+\\-]?[0-9]+(\\.[\\0-9]+)?$' END 
FROM `archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E`
LEFT OUTER JOIN `archived_161D0A92-6451-8D6F-E2E6-F11E326BDC57` AS `archived_161D0A92-6451-8D6F-E2E6-F11E326BDC57` ON FIND_IN_SET(`archived_161D0A92-6451-8D6F-E2E6-F11E326BDC57`.`f_161D0B12-47D0-440C-B3BE-7B602AB4B6C9`, `archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E`.`id`)
LEFT OUTER JOIN `archived_161D0F26-EF10-0144-96E5-054826F06E76` AS `archived_161D0F26-EF10-0144-96E5-054826F06E76` ON FIND_IN_SET(`archived_161D0F26-EF10-0144-96E5-054826F06E76`.`f_161D0F27-FD11-15DB-468F-E4F1B26297AD`, `archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E`.`id`)
WHERE (`archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E`.status != 0 ) 
AND (`archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E`.`f_161D0A43-0F71-3489-93FC-6819A5E020DA`  LIKE '123 %' )
GROUP BY `archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E`.id) THEN 'COUNT' ELSE 'SUM' END

CCJSqlParserUtil.parse(**this sql**)  will throw error

but remove  **REGEXP '^[\\+\\-]?[0-9]+(\\.[\\0-9]+)?$'**  in this sql  will convert complete

java 1.8
jsqlparse 1.2  relaese

net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "IN" "IN"
    at line 1, column 22.

Was expecting one of:

    "&"
    "::"
    "<<"
    ">>"
    "THEN"
    "^"
    "|"

**Comment by wumpz** [comment]
Out of curiosity: which dB system is this? I only know regexp(val1, val2) as a function or is this a "matches" condition?

**Comment by coderstory** [comment]
mysql 5.7

**Comment by manticore-projects** [comment]
Your statement parses just fine and mysql `RLIKE` and `REGEXP` expressions are supported.
But you will need to quote your identifiers properly since `-` dashes are not allowed for identifiers and collide with minus operator.

[Please try it here online.](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEkEFQChZvRtB1AEiAcrAOQAMRsAkoQBSygQzxIiqZvsefZ6EBEAhgCcAxgAsAlgDcApgBMA+gEYAbIoAiJBIpABaDcpI6QATkgBmHQHZLxhDoQIzqgCwAhTQDEArCF4A6XgAzJVUNR0Udc1VIj0hjHTMPZwsvSzMADjUQLMVndNdeWABeYiJWLgrKzGgeYkUyqsaK8FBYAREJGQUVdU1tPRIDI1MLa1t7Rxd3BG9fAOCesLMIqJXY+MTknVSMrJy8gtgAJRAAcRAADQAFYgA9AG0AHQBqR50AXQB+e8Njd+fqI8-E9fv8AJSfAAkDSasIwBDU5ThbA8RwA8gBZNpCMRSOQhXpaXT6QwmcxWGx2BxOXLTWa8JHItgQDxwNEAVWgICOsAAUmiqNiOnjuqFNMYAEw6ZTOLwRTLKDxGCUgZQ6DyKbRmCXKVxqSCpQpIIW4roEsKS6Wy+VqRXK1XqzUgbW6-WGxlMthowgecQAOwUFD98mA0gALrR2qb8YtxVKZXKdAqlSAVWqNVqdXqDZZ-EFzSRXIopc5LBodM5nCRIDpXGZXLpLK4DBKEK43Mo4rwADQmzoxsVEgZDMmjSkTGluTw+fziWSwMEez1oFlszncvkCvg4-ui3oeHVGDWGEi5Zw6YzKEBeHQkLx5HUeQYgSzKI3APsigsHtUgY+3s8LyvG87wfRVn1fBll04b1YF9AN5CDENw0jHcv1jH8j0UE9AMva9b3vdJHwgt95m-CVLHVNRNR0RQvDUVwK2UdIU2cDVXB1CVjEsBA1B7T8zVjIcSWGckxipSZaWnOY5wXJcmVwbkQFgVDhUEwd+hE0cKXGakpmk-wAGcw34MMAFdDNgABCEoSDk6C2AQfA1BUgSB0JTTBlJEYdIkyc6RnMihK2EgPEsCIzDyeJjESGtmMUWwfBICUSDUBBCjACgAGllKIYszFgABSchFwc9BTnRdkblcABNNy9zCTyRx88SJ30mZAtk0qqhqAhiEgDl8GgGEuBaXLgHZDERvYBFkAAbiAA)

```sql
SELECT CASE
            WHEN '0' IN ( SELECT CASE
                                      WHEN "archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E"."f_161D0A31-C361-CFC9-3F43-5738DEDE148B" = ''
                                        THEN '1'
                                      ELSE "archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E"."f_161D0A31-C361-CFC9-3F43-5738DEDE148B" REGEXP '^[\+\-]?[0-9]+(\.[\0-9]+)?$'
                                    END
                          FROM "archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E"
                            LEFT OUTER JOIN "archived_161D0A92-6451-8D6F-E2E6-F11E326BDC57" AS "archived_161D0A92-6451-8D6F-E2E6-F11E326BDC57"
                              ON Find_In_Set( "archived_161D0A92-6451-8D6F-E2E6-F11E326BDC57"."f_161D0B12-47D0-440C-B3BE-7B602AB4B6C9", "archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E".id )
                            LEFT OUTER JOIN "archived_161D0F26-EF10-0144-96E5-054826F06E76" AS "archived_161D0F26-EF10-0144-96E5-054826F06E76"
                              ON Find_In_Set( "archived_161D0F26-EF10-0144-96E5-054826F06E76"."f_161D0F27-FD11-15DB-468F-E4F1B26297AD", "archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E".id )
                          WHERE ( "archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E".status != 0 )
                            AND ( "archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E"."f_161D0A43-0F71-3489-93FC-6819A5E020DA" LIKE '123 %' )
                          GROUP BY "archived_161D0A1E-D060-E9C3-779A-AA3614B0AF5E".id )
              THEN 'COUNT'
            ELSE 'SUM'
          END
;
```
