### ISSUE TITLE
Boolean expressions are not parsed

### ISSUE THREAD

**Issue by olavloite** [JSQLParser/JSqlParser#658]
### Actual Behavior
The following select throws an `JSQLParserException`
`SELECT 2>1 AS FOO FROM BAR`

### Expected Behavior
`SELECT 2>1 AS FOO FROM BAR` should not throw an exception and the `2>1` should be recognized as a boolean expression.

### Steps to Reproduce the Problem

  1. Try to parse `SELECT 2>1 AS FOO FROM BAR`
  1. Verify that an exception is thrown

### Specifications

  - Version: 1.3
  - Platform:
  - Subsystem:

**Comment by zhztheplayer** [comment]
AFAIK The boolean expression including the `TRUE`, `FALSE` literal is not supported in JSqlParser currently. I used to try to add such a support and ended up with a quick-and-dirty solution. I recall that the parsing performance falls a lot due to adding more syntactic LOOKAHEADs.

I would like to try contribute a better solution once I solved the performance problem.

**Comment by wumpz** [comment]
Could you try a more recent version. There were changes using relations as parameters.

**Comment by zhztheplayer** [comment]
> Could you try a more recent version. There were changes using relations as parameters.

Ahh. I think I missed the feature, thank you very much for the work, @wumpz.
Besides, after searching the tokens in parser file I think that the `TRUE` / `FALSE` literal are still not supported yet. But that part seems to be something trivial.

**Comment by wumpz** [comment]
What do you mean by TRUE / FALSE are not supported? They should be parsed as column names, but it should work.

**Comment by zhztheplayer** [comment]
Yes, it should work, and it does not fail parsing if I use SQL like `SELECT CASE x WHEN TRUE THEN ...`. 

But I'd like to see a `BooleanValue()` production added to parser file, as well as existing `DoubleValue()`, `LongValue()`, etc (see below). So that we can distinguish the literal values from column names.

https://github.com/JSQLParser/JSqlParser/blob/97797425f6356216d0c4428c7e33ee94567d7271/src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt#L2715-L2717

**Comment by sivaraam** [comment]
> Could you try a more recent version. There were changes using relations as parameters.

I tried using version 3.0 and I am unable to parse the following query,

```sql
SELECT (emp_name <> 'ron' AND emp_name != 'rick') FROM employee;
```

Code snippet:

```java
        try {
            Statement conditionalsInSelectColumn =
                    CCJSqlParserUtil.parse("SELECT (emp_name <> 'ron' AND emp_name != 'rick') FROM employee;");
        } catch (JSQLParserException e) {
            e.printStackTrace();
        }
```

**Comment by wumpz** [comment]
was already solved

**Comment by wumpz** [comment]
ups reopened again, the last problem was not solved

**Comment by manticore-projects** [comment]
[Works with 4.1](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEAUsCmBbADgfQHYEMVNgB4A+WAcgCcB7LMgKFkaeZdgEEA5AEWXWzwIBCALzkKASwDGAazKwAlHQBiAJQDyAWV5oANlQCeSJHQDcdc6AgxYAJlikAjO2CwAZlSrL1WgEY4KpkA+)
