### ISSUE TITLE
SQL解析错误

### ISSUE THREAD

**Issue by walh1314** [JSQLParser/JSqlParser#683]
###Actual Behavior
 CCJSqlParserManager parser = new CCJSqlParserManager();
Statement stmt = parser.parse(new StringReader("select 9999name from table"));
###Expected Behavior
select 9999 name from table
###Steps to Reproduce the Problem

  1. SQL语句如果出现 select 9999name from table,会解析为select 9999 name from table

### Specifications

  - Version:1.2
  - Platform:java
  - Subsystem:

**Comment by wumpz** [comment]
JSqlParser does not support column or table names starting with a number.

**Comment by walh1314** [comment]
> JSqlParser does not support column or table names starting with a number.

当前这种语句可以出现在JSqlParser ，并且会解析成这种格式

**Comment by walh1314** [comment]
> JSqlParser does not support column or table names starting with a number.

语法匹配的时候没有判断后面的是字母还是其他运算符

**Comment by wumpz** [comment]
Please use English. That is the common language of our developers. Thx

**Comment by walh1314** [comment]
> Please use English. That is the common language of our developers. Thx
> 
> PS: using google translator I did not understand your argument. The problem is e.g. 1e10 is a valid postgresql number. You could work around your issue by quote your column like "9999name". This is standard sql behaviour.

Questions are as follows:
When "select cloumn1 , 3333cloumn2 from table " appears in the query statement, the SQL statement should report an error, but after jsqlparse, the Statement will become "select cloumn1 , 3333 cloumn2 from table", or when useAs is true, Statement will Becomes "select cloumn1 , 3333 AS cloumn2 from table" but this is not the result I want and does not conform to the SQL syntax specification.

**Comment by wumpz** [comment]
Aha. Understood. For JSqlParser like for many other db systems this is the valid behaviour. Postgresql e.g. can successfully execute 

`select 5a `

resulting in 5 is the value and the column name is a.

**Comment by walh1314** [comment]
> Aha. Understood. For JSqlParser like for many other db systems this is the valid behaviour. Postgresql e.g. can successfully execute
> 
> `select 5a`
> 
> resulting in 5 is the value and the column name is a.

But Mysql database does not support, if you do not need support, how to modify the configuration or code, Thx

**Comment by wumpz** [comment]
So you want to fail JSqlParser in this context?

That would be hard to achieve, due to JavaCC generates the parser. Maybe one way would be to make the parser parse it as a column name and then fail it in semantic check afterwards.

To allow this you had to start in JSqlParser.jjt line 345 define the S_IDENTIFIER like

<S_IDENTIFIER: <PART_LETTER>+>

Then you need to correct all following grammar problems, like number parsing 1e10 etc.

And that will be only the beginning. 



Maybe a simpler solution would be to check if the parsed column name within your sql is directly prefixed by a number. To get the direct column name position within your SQL you need the corresponding AST nodes. Look at SelectASTTest.java to get an idea of what I mean. 

I would go this way.
