### ISSUE TITLE
Nested concat taking days to parse.

### ISSUE THREAD

**Issue by Parth59** [JSQLParser/JSqlParser#766]
### Actual Behavior
JSQLparser is unable to parse sql with more than 20 nested concats.

### Expected Behavior
Should be able to parse the nested sql statements.

### Steps to Reproduce the Problem
Input sql 
select concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat(concat('1','2'),'3'),'4'),'5'),'6'),'7'),'8'),'9'),'10'),'11'),'12'),'13'),'14'),'15'),'16'),'17'),'18'),'19'),'20'),'21'),col1 from tbl t1

The following code block takes a lot of time to process.
  1.        Statement statement = CCJSqlParserUtil.parse(content);
  

### Specifications

  - Version: 1.4
  - Platform: MAC with java 1.8
  - Subsystem: UNIX

**Comment by wumpz** [comment]
That is an official problem, that JSqlParser has a hard time parsing those nested bracket constructs.

**Comment by Parth59** [comment]
Can't it be optimised ?
Or is there a possibility to restructure the sql at runtime to select concat('1','2','3','4','5','6','7','8','9','10','11','12','13','14,'15','16','17','18','19','20','21'),col1 from tbl t1 ?

**Comment by wumpz** [comment]
Restructuring the sql would surely be a solution, but I consider this simply a hack. As I told you, it is already a known problem. The right solution is to adapt JSqlParser to parse it fast :). I can tell you, that JSqlParser is somehow stuck within recursive lookahead calls. 

There is another project within JSqlParser organisation that aims to provide some performance test tools. Nevertheless it is very technical.

Do you want to investigate more? I could give you more informations or you keep on waiting a little bit more, because I am already on it without knowning, how long it will take?

**Comment by Parth59** [comment]
I was using jsqlparser 1.4  which couldn't parse a single query in an hour but now when i changed back to version 1.2, I could find that the query was successfully parsed in 20 -30 seconds.  
Could you please have a look into it ?

**Comment by wumpz** [comment]
Could you check it. I just deployed a new 2.1-SNAPSHOT. Your statement is parsed within 3 secs on my computer. This seems to be a huge achievement to days. ;)
