### ISSUE TITLE
Processing nested WITH's

### ISSUE THREAD

**Issue by v9854268996** [JSQLParser/JSqlParser#839]
Parser does not properly process nested WITH's and throws exception

example:
CCJSqlParserUtil.parse(sql) fails on SQL:

```
select 1
from (with sel as 
		(select 1 ) 
	  select 1
	  from sel ) first
```

### Specifications

  - Version: 2.1
  - Platform: windows
  - Subsystem:

**Comment by wumpz** [comment]
With statements are expected to come first, at least for JSqlParser at this time. PRs are welcome.

**Comment by wumpz** [comment]
This was a hard nut to crack. ;) However syntactically JSqlParser is able to parse your statement. The problem is that in a former issue an improvement for **teradata** syntax. There you can shortcut **select** by **sel**. That is exactly the table name you used.

`select 1 from (with mytable1 as (select 2 ) select 3 from mytable1 ) first`

is parsed perfectly well.
