### ISSUE TITLE
Column name 'size' is now no more accepted

### ISSUE THREAD

**Issue by eolivelli** [JSQLParser/JSqlParser#867]
**Describe the bug**
In jSQLParser 3.0 it is no more possible to have column names with name 'size'

**To Reproduce**
```
CREATE TABLE table (
     pk int PRIMARY KEY,
     size int
)
```
3. Exception
 ```
Encountered unexpected token: "size" "SIZE"
    at line 1, column 52.

Was expecting one of:

    "ACTION"
    "ANY"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHAR"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "DESCRIBE"
    "DO"
    "DUPLICATE"
    "ENABLE"
    "END"
    "EXCLUDE"
    "EXTRACT"
    "FALSE"
    "FIRST"
    "FN"
    "FOLLOWING"
    "INDEX"
    "INSERT"
    "INTERVAL"
    "ISNULL"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "NEXTVAL"
    "NO"
    "NULLS"
    "OPEN"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "READ"
    "REPLACE"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SIBLINGS"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUE"
    "TRUNCATE"
    "TYPE"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "XML"
    "ZONE"
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:21726)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:21573)
	at net.sf.jsqlparser.parser.CCJSqlParser.CreateTable(CCJSqlParser.java:12199)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:165)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:75)
	at herddb.sql.DDLSQLPlanner.parseStatement(DDLSQLPlanner.java:251)
	... 30 more
```

**Expected behavior**
No error

As a workaround the user can use the backticks syntax but the real problem is that exising downstream clients of HerdDB won't be able to run their scripts without changing the application.
Is is possible to add a white list of non-reserved words or configure some "dialect" ?
With a little hint we (HerdDB community) will be happy to contribute a patch

**System**
 - Database you are using
HerdDB
- Java Version
Not important
- JSqlParser version
3.0

**Comment by eolivelli** [comment]
downstream issue on HerdDB https://github.com/diennea/herddb/pull/481

**Comment by wumpz** [comment]
@eolivelli Sorry about that. This regression was introduced by some PR. So I included a test case espescialy for this column name. The corrected version is not yet deployed, but if you compile it yourself, it is useable.

**Comment by eolivelli** [comment]
@wumpz thank you.
Usual question....is any release planned in the near future ?

cc @diegosalvi @amitvc

**Comment by eolivelli** [comment]
@wumpz do you have time for a 3.0.1 release ?
this way we can pick up this fix and move to jsqlparser 3.x our project

thanks in advance

**Comment by wumpz** [comment]
I have one large open issue (cross apply). After that I will release. 
-------- Ursprüngliche Nachricht --------Von: Enrico Olivelli <notifications@github.com> Datum: 04.11.19  13:34  (GMT+01:00) An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> Cc: Tobias <t.warneke@gmx.net>, Mention <mention@noreply.github.com> Betreff: Re: [JSQLParser/JSqlParser] Column name 'size' is now no more
  accepted (#867) @wumpz do you have time for a 3.0.1 release ?
this way we can pick up this fix and move to jsqlparser 3.x our project
thanks in advance

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JSQLParser/JSqlParser/issues/867?email_source=notifications\u0026email_token=AAL7EOLGYWOOLIURWDJM3WDQSAJELA5CNFSM4I63BVZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC7CVNY#issuecomment-549333687",
"url": "https://github.com/JSQLParser/JSqlParser/issues/867?email_source=notifications\u0026email_token=AAL7EOLGYWOOLIURWDJM3WDQSAJELA5CNFSM4I63BVZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC7CVNY#issuecomment-549333687",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
