### ISSUE TITLE
How do I add functions to columns

### ISSUE THREAD

**Issue by chen-ABC** [JSQLParser/JSqlParser#943]
example：
`select a.num/2  where a,b where a.id=b.id`
=> add functions to all columns
`select  decode(a.num,'key')/2  where a,b where decode(a.id,'key')=decode(b.id,'key')`

I tried using the API
`new ExpressionVisitorAdapter() {
    @Override
    public void visit(Column column) {
        column.setColumnName("decode("+column.getColumnName()+",key')");
    }
}`
But the results were not expected:
`select  a.decode(num,'key')/2  where a,b where a.decode(id,'key')=b.decode(id,'key')`
How do I make a function contain table and column names

**Comment by wumpz** [comment]
That is a very tricky one to solve because You don't know from where you come from, where to put the changes in. To sketch the solution:

1. Use the ExpressionVisitorAdapter and maintain or build a parent-child hierarchy, while calling.
2. Then the column would know, where it came from and could replace the content there.
3. Build a function item and do not replace the column's name.

Another solution would be (a little hack) to replace the occurrences within the original SQL. JSqlParser does deliver a rudimentary AST with column text positions within your original SQL.

These variants would give you a general solution. But if you already know the structure of you SQL better, e.g. only columns that are direct select items and directly used within your where clause, that would make things much easier.

**Comment by wumpz** [comment]
This would be a very light variant to replace all direct used columns within the where statement:

```Java
public class SimpleSqlParser33ReplaceColumnsByFunctions {

    public static void main(String args[]) throws JSQLParserException {
        Select stmt = (Select) CCJSqlParserUtil.parse("select a.num/2 from a,b where a.id=b.id");
        System.out.println("before " + stmt.toString());

        ((PlainSelect) stmt.getSelectBody()).getWhere().accept(new ExpressionVisitorAdapter() {
            @Override
            public void visitBinaryExpression(BinaryExpression expr) {
                expr.setLeftExpression(buildFunction(expr.getLeftExpression()));
                expr.setRightExpression(buildFunction(expr.getRightExpression()));
            }

        });

        System.out.println("after " + stmt.toString());
    }

    private static Expression buildFunction(Expression expr) {
        if (expr instanceof Column) {
            Function func = new Function();
            
            func.setName("decode");
            func.setParameters(new ExpressionList(expr, new StringValue("'key'")));
            return func;
        } else return expr;
    }
}

```
But as I saw, you want to replace columns within expressions as well **a.num/2**.  So there work is to be done.

**Comment by chen-ABC** [comment]
@wumpz  Thanks. I see
