### ISSUE TITLE
Fully qualified Postgres functions incorrectly parsed

### ISSUE THREAD

**Issue by SerialVelocity** [JSQLParser/JSqlParser#944]
When parsing something like:
```
SELECT pg_catalog.now()
```

Expected behaviour is for the function name to be `now` with a schema name of `pg_catalog`.

Instead, there is no `getSchemaName` method and the `getName` returns `pg_catalog.now`.

**System**
- Database you are using: Postgres
- Java Version: 11
- JSqlParser version: 3.1

**Comment by wumpz** [comment]
Using columns or tables this is solved using a multipart name behind the scenes. One could implement this here as well. Since JSqlParser wants to provide parsing for multiple DB dialects it is not clear, what the first part of **pg_catalog.now()** really is. For instance using JQL from some JPA stuff, it could be a package name.

**Comment by wumpz** [comment]
Now JSqlParser supports multipart names for functions.
