### ISSUE TITLE
whereSql end with ' xxx is not null '  after parse ' xxx ' is not null  run away 

### ISSUE THREAD

**Issue by BigBroB** [JSQLParser/JSqlParser#956]
#### Describe the bug
whereSql end with ' xxx is not null '  after parse ' xxx ' is not null  run away 

##### 
1. Example SQL
```
SELECT * FROM  t WHERE id is not null
```
2. Parsing this SQL using JSqlParser with this statements
```
        String sql = "SELECT * FROM  t WHERE id is not null";
        Statement stmt = CCJSqlParserUtil.parse(sql);
        Select select = (Select) stmt;
        SelectBody selectBody = select.getSelectBody();
        PlainSelect body = (PlainSelect) selectBody;
        Expression where = body.getWhere();
        String newWhereStr = new StringBuilder(where.toString()).append("AND ").append("id = 1").toString();
        Expression newWhere = CCJSqlParserUtil.parseCondExpression(newWhereStr);
        body.setWhere(newWhere);
        sql = select.toString();
        System.out.println(sql);
```
3. Exception
print sql 
```
SELECT * FROM  t WHERE id 
```

**Expected behavior**
`is not null`  should not be eaten 

**System**
 - Database you are using
- Java Version 1.8
- JSqlParser version 3.1

**Comment by wumpz** [comment]
Strange. I will look into it.

**Comment by wumpz** [comment]
The problem lies within your code. The rebuild **where** expression of yours is:

    id IS NOT NULLAND id = 1

See the missing space?

The method **CCJSqlParserUtil.parseCondExpression** parses a condition as far as possible. If you want the whole string to be parsed, you have the second parameter to forbid this partial parsing.

If you correct the where statement the resulting statement is correct.

**Comment by BigBroB** [comment]
thank you . When whereToString ,String be trimed .
