### ISSUE TITLE
Foreign key specification

### ISSUE THREAD

**Issue by wise-coders** [JSQLParser/JSqlParser#981]
Parsing MySql scripts containing foreign keys specified like:

ALTER TABLE `atconfigpro`
  ADD CONSTRAINT `atconfigpro_atconfignow_id_foreign` FOREIGN KEY (`atconfignow_id`) REFERENCES `atconfignow` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `atconfigpro_attariff_id_foreign` FOREIGN KEY (`attariff_id`) REFERENCES `attariff` (`id`) ON DELETE CASCADE;

fails with 
Encountered unexpected token: "ON" "ON"
    at line 2, column 94.

Can you please add support for this ? I was checking if I can contribute to this, but I need first to learn the jjt.

**Comment by Atrenti** [comment]
thanks for trying to help us with this issue. Unfortunately it's a showstopper we need to resolve to achieve an importan milestone. thanks in advance for helping. Juan

**Comment by wumpz** [comment]
That sounds realy ugent. I will look into it. My first guess is, that this syntactical construct of **on delete cascade** is simply not supported yet.

**Comment by wumpz** [comment]
I deployed a new 3.2-SNAPSHOT version with this change. Could you check it.

**Comment by wise-coders** [comment]
Thank you very much.

I have issues installing the jar. I use gradle with dependency on mavenCentral(), and I see there the 3.2-SNAPSHOT is not yet published there. On website it says is in sonatype. Is it possible to push 3.2-SHAPSHOT also in mavenCentral() ?

Do you know how may I include the sonatype public repository in the gradle list of repositories ?

I tried something like in this article, but it doesn't work:
[1] https://blog.sonatype.com/new-sonatype-scan-gradle-plugin

I tried also doing git clone jsqlparser, then mvn clean install but I get:

C:\Software\jdk-13.0.2\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\Temp\JSqlParser "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\plugins\maven\lib\maven3\bin\m2.conf" -Didea.launcher.port=59509 "-Didea.launcher.bin.path=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMainV2 org.codehaus.classworlds.Launcher -Didea.version=2018.3.5 org.apache.maven.plugins:maven-install-plugin:2.5.2:install

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JSQLParser library 3.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-cli) @ jsqlparser ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.029 s
[INFO] Finished at: 2020-05-09T07:58:20+02:00
[INFO] Final Memory: 10M/44M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-cli) on project jsqlparser: The packaging for this project did not assign a file to the build artifact -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] [2] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1

I am not an expert into this, maybe you can help.

Best regards,
 Dragos Pruteanu

--
 DbSchema - Wise Coders GbmH
82256 Fürstenfeldbruck bei München
 Email: support@dbschema.com - Web: [3] http://dbschema.com/

--

[1] https://blog.sonatype.com/new-sonatype-scan-gradle-plugin
[2] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[3] http://www.example.com/

**Comment by wumpz** [comment]
Snapshots are not published at maven central. Use the Sonatype repo. I think there is at least a maven type explanation at readme. Cheers Tobias
-------- Ursprüngliche Nachricht --------Von: Wise Coders <notifications@github.com> Datum: 09.05.20  08:14  (GMT+01:00) An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> Cc: Tobias <t.warneke@gmx.net>, State change <state_change@noreply.github.com> Betreff: Re: [JSQLParser/JSqlParser] Foreign key specification (#981) 

Thank you very much.



I have issues installing the jar. I use gradle with dependency on mavenCentral(), and I see there the 3.2-SNAPSHOT is not yet published there. On website it says is in sonatype. Is it possible to push 3.2-SHAPSHOT also in mavenCentral() ?



Do you know how may I include the sonatype public repository in the gradle list of repositories ?



I tried something like in this article, but it doesn't work:

[1] https://blog.sonatype.com/new-sonatype-scan-gradle-plugin



I tried also doing git clone jsqlparser, then mvn clean install but I get:



C:\Software\jdk-13.0.2\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\Temp\JSqlParser "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\plugins\maven\lib\maven3\bin\m2.conf" -Didea.launcher.port=59509 "-Didea.launcher.bin.path=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMainV2 org.codehaus.classworlds.Launcher -Didea.version=2018.3.5 org.apache.maven.plugins:maven-install-plugin:2.5.2:install



[INFO] Scanning for projects...

[INFO]

[INFO] ------------------------------------------------------------------------

[INFO] Building JSQLParser library 3.2-SNAPSHOT

[INFO] ------------------------------------------------------------------------

[INFO]

[INFO] --- maven-install-plugin:2.5.2:install (default-cli) @ jsqlparser ---

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 1.029 s

[INFO] Finished at: 2020-05-09T07:58:20+02:00

[INFO] Final Memory: 10M/44M

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-cli) on project jsqlparser: The packaging for this project did not assign a file to the build artifact -> [Help 1]

[ERROR]

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.



[ERROR]

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] [2] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException



Process finished with exit code 1



I am not an expert into this, maybe you can help.



Best regards,

 Dragos Pruteanu



--

 DbSchema - Wise Coders GbmH

82256 Fürstenfeldbruck bei München

 Email: support@dbschema.com - Web: [3] http://dbschema.com/



--



[1] https://blog.sonatype.com/new-sonatype-scan-gradle-plugin

[2] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

[3] http://www.example.com/



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/JSQLParser/JSqlParser/issues/981#issuecomment-626113471",

"url": "https://github.com/JSQLParser/JSqlParser/issues/981#issuecomment-626113471",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by wumpz** [comment]
Sorry I didn't see your last comment about building it. I use Java 8 to build JSqlParser and maven 3.3 or 3.6. Both worked.
